export const CONTENT = {
  en: {
    nav: { about: 'About Us', services: 'Services', pricing: 'Pricing', help: 'Help', contact: 'Contact', feedback: 'Feedback', getStarted: 'Get Started', forRecruiters: 'For Recruiters' },
    footer: {
      tagline: 'Get past the bots. Get in front of the humans.',
      product: 'Product', services: 'Services', pricing: 'Pricing', tryFree: 'Try it free',
      company: 'Company', about: 'About Us', contact: 'Contact', terms: 'Terms of Service', privacy: 'Privacy Policy',
      followUs: 'Follow us', rights: 'All rights reserved.',
    },
    home: {
      badge: 'AI-powered résumé tailoring',
      headline1: 'Your résumé might be getting rejected',
      headline2: 'before a human ever reads it.',
      sub: "Most mid-size and large employers filter applications with ATS software before a recruiter opens them. Resemy rewrites your résumé to get through — and shows you the score, before and after.",
      ctaPrimary: 'Try it free', ctaSecondary: 'See how it works',
      stat1Value: '60s', stat1Label: 'Typical tailoring time',
      stat2Value: '$0', stat2Label: 'To get started',
      stat3Label: 'Languages supported',
      heroImgAlt: 'Person confidently working on a laptop',
      problemLabel: 'The problem',
      problemTitle: 'Qualified. Experienced. Still getting filtered out.',
      problemDesc: "It's rarely about your skills. Applicant Tracking Systems scan for specific keywords and structure — and a résumé that doesn't speak the job posting's exact language often never reaches a person at all.",
      beforeLabel: 'Example — before',
      beforeDesc: 'Generic résumé, same for every application — missing the exact terms this job is scanning for.',
      afterLabel: 'Example — after Resemy',
      afterDesc: "Same real experience, rewritten in the job posting's own language — nothing invented, just translated.",
      howLabel: 'How it works', howTitle: 'Ready in about a minute',
      step1Title: 'Upload your résumé', step1Desc: 'A PDF, a DOCX, or just paste the text — whatever you already have.',
      step2Title: 'Paste the job posting', step2Desc: 'The full job description, so Resemy knows exactly what to match.',
      step3Title: 'Download, tailored', step3Desc: 'A rewritten résumé, your ATS + Manager score, and what to do next.',
      featuresLabel: 'Everything included', featuresTitle: 'More than just a rewrite',
      feature1Title: 'Tailored résumé', feature1Desc: 'Rewritten to match this specific job — never fabricated experience.',
      feature2Title: 'Cover letter & email', feature2Desc: 'A matching cover letter and a short application email, generated together.',
      feature3Title: 'Reference letter drafts', feature3Desc: 'A starting draft for your references to personalize and sign.',
      feature4Title: 'Interview prep', feature4Desc: 'Likely questions, STAR-method scenarios, and what to ask them back.',
      feature5Title: 'Honest scoring', feature5Desc: "See your real before-and-after match — and what's genuinely still missing.",
      feature6Title: 'For recruiters too', feature6Desc: 'Screen candidates against a posting in seconds with our HR tool.',
      finalTitle: 'Stop getting filtered out.', finalSub: 'Free to start. No credit card required.', finalCta: 'Get Started free',
      globalTitle: 'Made in Canada. Built for the world.',
      globalSub: "Whether you're applying down the street or across the globe, Resemy works the same honest way for everyone — wherever you're headed next.",
      recruitersTitle: "Screening resumes shouldn't take all day.",
      recruitersSub: "Resemy evaluates each candidate against the job you're hiring for — so you spend less time reading resumes and more time talking to the right people.",
    },
        about: {
      label: 'About us', title: 'About Resemy',
      p1: "Resemy Solutions is a new company, registered in British Columbia, Canada. We started with a pattern we kept seeing in job searches: talented people either stuff their resume with keywords they can't back up to get past the ATS, or they don't tailor it at all and get filtered out anyway. Neither one works.",
      p2: "Resemy, our first product, takes a different approach. It rewrites your resume to genuinely match a job description — using your real experience, reworded and reorganized around what the posting actually asks for — without inventing a skill, employer, or achievement that isn't yours. You can see it working: your match score improves from your original resume to the tailored one, honestly.",
      p3: "This is our starting point, not the finish line — we're actively building the next set of tools on the same principle: help you present your real experience in the strongest possible light, never a fabricated one. If Resemy helps you land an interview, we'd love to hear about it — we're small enough right now that your feedback shapes what we build next.",
    },
    services: {
      label: 'Our services', title: 'One tool, two sides of hiring',
      sub: "Whether you're applying or hiring, Resemy is built around the same honest principle: real information, clearly scored.",
      candidatesTitle: 'For Candidates',
      c1t: 'Tailored résumé rewriting', c1d: "Your résumé, rewritten to match a specific job posting's language and requirements.",
      c2t: 'ATS & Manager scoring', c2d: 'An honest before-and-after score, plus exactly which keywords are matched or missing.',
      c3t: 'Cover letters & application emails', c3d: 'A matching cover letter and a short, confident application email — generated together.',
      c4t: 'Reference letter drafts', c4d: "A starting draft for one of your real references to personalize and sign.",
      c5t: 'Interview preparation', c5d: 'Likely questions, example answers, STAR-method scenarios, and smart questions to ask back.',
      hrTitle: 'For HR & Recruiters',
      h1t: 'Candidate screening', h1d: "Upload a candidate's résumé and a job posting to get an instant, consistent evaluation.",
      h2t: 'Strengths & gap analysis', h2d: 'Matched requirements, missing requirements, and anything worth double-checking before an interview.',
      h3t: 'Downloadable assessment reports', h3d: 'A clean, shareable .docx report for every candidate you screen.',
      cta: 'Try it free',
    },
    contact: {
      label: 'Contact', title: 'Get in touch',
      sub: 'Questions, feedback, or partnership ideas — we read every message.',
      nameLabel: 'Name', emailLabel: 'Email', messageLabel: 'Message',
      send: 'Send message', sending: 'Sending…',
      sentMsg: "Thanks — your message is on its way. We'll get back to you soon.",
      errorGeneric: 'Something went wrong.',
    },
  },

  ar: {
      nav: { about: 'من نحن', services: 'خدماتنا', pricing: 'الأسعار', help: 'المساعدة', contact: 'اتصل بنا', feedback: 'ملاحظات', getStarted: 'ابدأ الآن', forRecruiters: 'للموارد البشرية' },
    footer: {
      tagline: 'تجاوز برامج الفرز. تواصل مباشرة مع البشر.',
      product: 'المنتج', services: 'الخدمات', pricing: 'الأسعار', tryFree: 'جرّبه مجانًا',
      company: 'الشركة', about: 'من نحن', contact: 'اتصل بنا', terms: 'شروط الخدمة', privacy: 'سياسة الخصوصية',
      followUs: 'تابعنا', rights: 'جميع الحقوق محفوظة.',
    },
    home: {
      badge: 'تخصيص السيرة الذاتية بالذكاء الاصطناعي',
      headline1: 'قد تُرفض سيرتك الذاتية',
      headline2: 'قبل أن يقرأها أي إنسان على الإطلاق.',
      sub: 'تستخدم معظم الشركات المتوسطة والكبيرة برامج تتبع المتقدمين (ATS) لفرز الطلبات قبل أن يفتحها أي مسؤول توظيف. يعيد Resemy كتابة سيرتك الذاتية لتجاوز هذا الفرز — ويعرض لك الدرجة، قبل التعديل وبعده.',
      ctaPrimary: 'جرّبه مجانًا', ctaSecondary: 'شاهد كيف يعمل',
      stat1Value: '60 ثانية', stat1Label: 'الوقت المعتاد للتخصيص',
      stat2Value: '0$', stat2Label: 'للبدء',
      stat3Label: 'لغات مدعومة',
      heroImgAlt: 'شخص يعمل بثقة على حاسوب محمول',
      problemLabel: 'المشكلة',
      problemTitle: 'مؤهل. لديه خبرة. ومع ذلك يُستبعد.',
      problemDesc: 'نادرًا ما يكون الأمر متعلقًا بمهاراتك. تبحث أنظمة تتبع المتقدمين عن كلمات مفتاحية وبنية محددة — والسيرة الذاتية التي لا تستخدم نفس لغة الإعلان الوظيفي غالبًا ما لا تصل إلى أي شخص على الإطلاق.',
      beforeLabel: 'مثال — قبل',
      beforeDesc: 'سيرة ذاتية عامة، متطابقة في كل طلب — تفتقر إلى المصطلحات الدقيقة التي تبحث عنها هذه الوظيفة.',
      afterLabel: 'مثال — بعد استخدام Resemy',
      afterDesc: 'نفس الخبرة الحقيقية، لكن معاد صياغتها بلغة الإعلان الوظيفي نفسها — لا شيء مُختلَق، فقط إعادة صياغة.',
      howLabel: 'كيف يعمل', howTitle: 'جاهز خلال دقيقة تقريبًا',
      step1Title: 'ارفع سيرتك الذاتية', step1Desc: 'ملف PDF أو DOCX، أو الصق النص مباشرة — أيًا كان ما لديك حاليًا.',
      step2Title: 'الصق الإعلان الوظيفي', step2Desc: 'الوصف الوظيفي كاملاً، ليعرف Resemy بالضبط ما يجب مطابقته.',
      step3Title: 'حمّلها، وهي مخصصة بالكامل', step3Desc: 'سيرة ذاتية معاد كتابتها، ودرجتا ATS والمدير، وما يجب فعله بعد ذلك.',
      featuresLabel: 'كل شيء متضمن', featuresTitle: 'أكثر بكثير من مجرد إعادة كتابة',
      feature1Title: 'سيرة ذاتية مخصصة', feature1Desc: 'معاد كتابتها لتناسب هذه الوظيفة تحديدًا — دون أي خبرة مُختلَقة أبدًا.',
      feature2Title: 'خطاب تقديم وبريد إلكتروني', feature2Desc: 'خطاب تقديم متوافق ورسالة تقديم قصيرة، يتم إنشاؤهما معًا.',
      feature3Title: 'مسودات خطابات توصية', feature3Desc: 'مسودة أولية ليقوم أحد مُزكّيك بتخصيصها والتوقيع عليها.',
      feature4Title: 'التحضير للمقابلة', feature4Desc: 'أسئلة متوقعة، وسيناريوهات بطريقة STAR، وأسئلة ذكية لطرحها بدورك.',
      feature5Title: 'تقييم صادق', feature5Desc: 'شاهد مدى التطابق الحقيقي قبل وبعد — وما الذي لا يزال ناقصًا فعليًا.',
      feature6Title: 'ولمسؤول التوظيف أيضًا', feature6Desc: 'قيّم المرشحين مقابل إعلان وظيفي خلال ثوانٍ باستخدام أداتنا الخاصة بالموارد البشرية.',
      finalTitle: 'توقف عن أن تُستبعد.', finalSub: 'مجاني للبدء. لا حاجة إلى بطاقة ائتمان.', finalCta: 'ابدأ مجانًا',
      globalTitle: 'صُنع في كندا، ومصمم للعالم كله.',
      globalSub: 'سواء كنت تتقدم لوظيفة قريبة منك أو في الجهة الأخرى من العالم، يعمل Resemy بنفس الطريقة الصادقة مع الجميع — أينما كانت وجهتك القادمة.',
      recruitersTitle: 'فرز السير الذاتية لا يجب أن يستغرق اليوم كله.',
      recruitersSub: 'يقيّم Resemy كل مرشح مقابل الوظيفة التي توظف لها — لتقضي وقتًا أقل في قراءة السير الذاتية ووقتًا أكثر في التحدث مع الأشخاص المناسبين.',
    },
        about: {
      label: 'من نحن', title: 'عن Resemy',
      p1: 'شركة Resemy Solutions هي شركة جديدة، مسجّلة في مقاطعة كولومبيا البريطانية، كندا. بدأنا لأننا لاحظنا نمطًا متكررًا في عمليات البحث عن عمل: فإما أن يحشو المرشحون المؤهلون سيرهم الذاتية بكلمات مفتاحية لا يملكون خبرة حقيقية تدعمها لتجاوز أنظمة تتبع المتقدمين (ATS)، أو لا يخصصون سيرهم الذاتية على الإطلاق فيتم استبعادهم على أي حال. لا يُجدي أي من الخيارين نفعًا.',
      p2: 'يتّبع Resemy، منتجنا الأول، نهجًا مختلفًا. فهو يعيد كتابة سيرتك الذاتية لتطابق إعلانًا وظيفيًا معينًا بصدق — باستخدام خبرتك الحقيقية، معاد صياغتها وتنظيمها وفق ما يطلبه الإعلان فعليًا — دون اختلاق مهارة أو جهة عمل أو إنجاز لا تملكه. ويمكنك أن ترى ذلك بنفسك: تتحسن درجة التطابق من سيرتك الذاتية الأصلية إلى النسخة المخصصة، بصدق تام.',
      p3: 'هذه نقطة انطلاقنا، لا خط النهاية — فنحن نعمل بنشاط على تطوير مجموعة أدوات جديدة تقوم على المبدأ نفسه: مساعدتك على عرض خبرتك الحقيقية بأقوى صورة ممكنة، دون اختلاق أي شيء أبدًا. وإذا ساعدك Resemy في الحصول على مقابلة عمل، يسعدنا أن نسمع ذلك منك — فنحن لا نزال صغيرين بما يكفي ليُشكّل رأيك ما سنبنيه لاحقًا.',
    },
    services: {
      label: 'خدماتنا', title: 'أداة واحدة، لوجهي التوظيف',
      sub: 'سواء كنت تتقدم لوظيفة أو توظّف، يقوم Resemy على المبدأ الصادق نفسه: معلومات حقيقية، وتقييم واضح.',
      candidatesTitle: 'للمتقدمين على الوظيفة',
      c1t: 'إعادة كتابة السيرة الذاتية بشكل مخصص', c1d: 'سيرتك الذاتية، معاد كتابتها لتطابق لغة ومتطلبات إعلان وظيفي محدد.',
      c2t: 'تقييم ATS والمدير', c2d: 'درجة صادقة قبل وبعد، بالإضافة إلى الكلمات المفتاحية المتطابقة أو الناقصة بالتحديد.',
      c3t: 'خطابات التقديم ورسائل التقديم', c3d: 'خطاب تقديم متوافق ورسالة تقديم قصيرة وواثقة، يتم إنشاؤهما معًا.',
      c4t: 'مسودات خطابات التوصية', c4d: 'مسودة أولية ليقوم أحد مُزكّيك الحقيقيين بتخصيصها والتوقيع عليها.',
      c5t: 'التحضير للمقابلات', c5d: 'أسئلة متوقعة، وأمثلة على الإجابات، وسيناريوهات بطريقة STAR، وأسئلة ذكية لطرحها بدورك.',
      hrTitle: 'للموارد البشرية ومسؤول التوظيف',
      h1t: 'فحص المرشحين', h1d: 'ارفع سيرة المرشح الذاتية وإعلان وظيفي للحصول على تقييم فوري ومتسق.',
      h2t: 'تحليل نقاط القوة والفجوات', h2d: 'المتطلبات المتوافقة، والمتطلبات الناقصة، وأي أمر يستحق التحقق منه قبل المقابلة.',
      h3t: 'تقارير تقييم قابلة للتحميل', h3d: 'تقرير واضح بصيغة Word، جاهز للمشاركة، لكل مرشح تقيّمه.',
      cta: 'جرّبه مجانًا',
    },
    contact: {
      label: 'اتصل بنا', title: 'تواصل معنا',
      sub: 'أسئلة أو ملاحظات أو أفكار شراكة — نقرأ كل رسالة تصلنا.',
      nameLabel: 'الاسم', emailLabel: 'البريد الإلكتروني', messageLabel: 'الرسالة',
      send: 'إرسال الرسالة', sending: 'جارٍ الإرسال…',
      sentMsg: 'شكرًا لك — رسالتك في طريقها إلينا. سنرد عليك قريبًا.',
      errorGeneric: 'حدث خطأ ما.',
    },
  },

  fr: {
        nav: { about: 'À propos', services: 'Services', pricing: 'Tarifs', help: 'Aide', contact: 'Contact', feedback: 'Commentaires', getStarted: 'Commencer', forRecruiters: 'Recruteurs' },
    footer: {
      tagline: 'Passez les bots. Parlez aux humains.',
      product: 'Produit', services: 'Services', pricing: 'Tarifs', tryFree: 'Essayer gratuitement',
      company: 'Entreprise', about: 'À propos', contact: 'Contact', terms: "Conditions d'utilisation", privacy: 'Politique de confidentialité',
      followUs: 'Suivez-nous', rights: 'Tous droits réservés.',
    },
    home: {
      badge: 'Optimisation de CV par IA',
      headline1: 'Votre CV est peut-être rejeté',
      headline2: "avant même qu'un humain ne le lise.",
      sub: "La plupart des moyennes et grandes entreprises filtrent les candidatures avec un logiciel ATS avant qu'un recruteur ne les ouvre. Resemy réécrit votre CV pour passer ce filtre — et vous montre le score, avant et après.",
      ctaPrimary: 'Essayer gratuitement', ctaSecondary: 'Voir comment ça marche',
      stat1Value: '60 s', stat1Label: "Temps moyen d'adaptation",
      stat2Value: '0 $', stat2Label: 'Pour commencer',
      stat3Label: 'Langues disponibles',
      heroImgAlt: 'Personne travaillant avec assurance sur un ordinateur portable',
      problemLabel: 'Le problème',
      problemTitle: 'Qualifié. Expérimenté. Toujours filtré.',
      problemDesc: "Ce n'est presque jamais une question de compétences. Les logiciels de suivi des candidatures (ATS) recherchent des mots-clés précis et une structure particulière — et un CV qui ne parle pas exactement le langage de l'offre d'emploi n'atteint souvent jamais un humain.",
      beforeLabel: 'Exemple — avant',
      beforeDesc: "CV générique, identique pour chaque candidature — sans les termes précis que ce poste recherche.",
      afterLabel: 'Exemple — après Resemy',
      afterDesc: "La même expérience réelle, réécrite dans le langage exact de l'offre d'emploi — rien n'est inventé, tout est reformulé.",
      howLabel: 'Comment ça marche', howTitle: 'Prêt en une minute environ',
      step1Title: 'Téléchargez votre CV', step1Desc: 'Un PDF, un DOCX, ou collez simplement le texte — ce que vous avez déjà.',
      step2Title: "Collez l'offre d'emploi", step2Desc: "La description complète du poste, pour que Resemy sache exactement quoi cibler.",
      step3Title: 'Téléchargez, sur mesure', step3Desc: 'Un CV réécrit, votre score ATS et recruteur, et les prochaines étapes.',
      featuresLabel: 'Tout est inclus', featuresTitle: "Bien plus qu'une simple réécriture",
      feature1Title: 'CV sur mesure', feature1Desc: "Réécrit pour correspondre à ce poste précis — jamais d'expérience inventée.",
      feature2Title: 'Lettre de motivation et e-mail', feature2Desc: "Une lettre de motivation assortie et un court e-mail de candidature, générés ensemble.",
      feature3Title: 'Ébauches de lettres de recommandation', feature3Desc: 'Un premier brouillon que vos références peuvent personnaliser et signer.',
      feature4Title: "Préparation à l'entretien", feature4Desc: "Questions probables, mises en situation selon la méthode STAR, et questions à poser en retour.",
      feature5Title: 'Notation honnête', feature5Desc: "Voyez votre véritable score avant/après — et ce qui manque réellement encore.",
      feature6Title: 'Pour les recruteurs aussi', feature6Desc: "Évaluez des candidats par rapport à une offre en quelques secondes grâce à notre outil RH.",
      finalTitle: 'Ne soyez plus jamais filtré.', finalSub: 'Gratuit pour commencer. Aucune carte bancaire requise.', finalCta: 'Commencer gratuitement',
      globalTitle: 'Conçu au Canada. Fait pour le monde entier.',
      globalSub: "Que vous postuliez tout près de chez vous ou à l'autre bout du monde, Resemy fonctionne de la même façon honnête pour tout le monde — où que vous alliez ensuite.",
      recruitersTitle: "Trier les CV ne devrait pas prendre toute la journée.",
      recruitersSub: "Resemy évalue chaque candidat par rapport au poste que vous recrutez — pour que vous passiez moins de temps à lire des CV et plus de temps à parler aux bonnes personnes.",
    },
        about: {
      label: 'À propos', title: 'À propos de Resemy',
      p1: "Resemy Solutions est une nouvelle entreprise, enregistrée en Colombie-Britannique, au Canada. Nous avons commencé en observant un schéma récurrent dans la recherche d'emploi : les candidats compétents surchargent leur CV de mots-clés qu'ils ne peuvent pas justifier pour passer les ATS, ou bien ils ne l'adaptent pas du tout et se font filtrer quand même. Aucune des deux approches ne fonctionne.",
      p2: "Resemy, notre premier produit, adopte une approche différente. Il réécrit votre CV pour qu'il corresponde réellement à une offre d'emploi — en utilisant votre véritable expérience, reformulée et réorganisée autour de ce que l'offre demande concrètement — sans jamais inventer une compétence, un employeur ou une réalisation que vous n'avez pas. Vous pouvez le constater : votre score de correspondance s'améliore, honnêtement, entre votre CV original et la version adaptée.",
      p3: "C'est notre point de départ, pas notre aboutissement — nous développons activement une nouvelle série d'outils fondés sur le même principe : vous aider à présenter votre véritable expérience sous son meilleur jour, jamais une expérience inventée. Si Resemy vous aide à décrocher un entretien, nous serions ravis de le savoir — nous sommes encore assez petits pour que vos retours façonnent ce que nous construisons ensuite.",
    },
    services: {
      label: 'Nos services', title: "Un seul outil, deux facettes du recrutement",
      sub: "Que vous postuliez ou que vous recrutiez, Resemy repose sur le même principe honnête : des informations réelles, clairement évaluées.",
      candidatesTitle: 'Pour les candidats',
      c1t: 'Réécriture de CV sur mesure', c1d: "Votre CV, réécrit pour correspondre au langage et aux exigences d'une offre d'emploi précise.",
      c2t: 'Notation ATS et recruteur', c2d: 'Un score honnête avant/après, ainsi que les mots-clés exacts trouvés ou manquants.',
      c3t: 'Lettres de motivation et e-mails de candidature', c3d: 'Une lettre de motivation assortie et un court e-mail de candidature confiant, générés ensemble.',
      c4t: 'Ébauches de lettres de recommandation', c4d: "Un premier brouillon que l'une de vos références réelles peut personnaliser et signer.",
      c5t: "Préparation à l'entretien", c5d: "Questions probables, exemples de réponses, mises en situation selon la méthode STAR, et questions pertinentes à poser en retour.",
      hrTitle: 'Pour les RH et les recruteurs',
      h1t: 'Présélection des candidats', h1d: "Téléchargez le CV d'un candidat et une offre d'emploi pour obtenir une évaluation instantanée et cohérente.",
      h2t: 'Analyse des forces et des lacunes', h2d: "Exigences satisfaites, exigences manquantes, et tout élément à vérifier avant un entretien.",
      h3t: "Rapports d'évaluation téléchargeables", h3d: "Un rapport clair au format .docx, prêt à partager, pour chaque candidat évalué.",
      cta: 'Essayer gratuitement',
    },
    contact: {
      label: 'Contact', title: 'Contactez-nous',
      sub: "Questions, commentaires ou idées de partenariat — nous lisons chaque message.",
      nameLabel: 'Nom', emailLabel: 'E-mail', messageLabel: 'Message',
      send: 'Envoyer le message', sending: 'Envoi en cours…',
      sentMsg: "Merci — votre message est en route. Nous vous répondrons bientôt.",
      errorGeneric: "Une erreur s'est produite.",
    },
  },

  es: {
        nav: { about: 'Sobre nosotros', services: 'Servicios', pricing: 'Precios', help: 'Ayuda', contact: 'Contacto', feedback: 'Comentarios', getStarted: 'Comenzar', forRecruiters: 'Reclutadores' },
    footer: {
      tagline: 'Supera a los robots. Llega a los humanos.',
      product: 'Producto', services: 'Servicios', pricing: 'Precios', tryFree: 'Pruébalo gratis',
      company: 'Empresa', about: 'Sobre nosotros', contact: 'Contacto', terms: 'Términos de servicio', privacy: 'Política de privacidad',
      followUs: 'Síguenos', rights: 'Todos los derechos reservados.',
    },
    home: {
      badge: 'Adaptación de currículums con IA',
      headline1: 'Es posible que tu currículum esté siendo rechazado',
      headline2: 'antes de que un humano lo lea.',
      sub: 'La mayoría de las empresas medianas y grandes filtran las solicitudes con software ATS antes de que un reclutador las abra. Resemy reescribe tu currículum para superar ese filtro, y te muestra la puntuación, antes y después.',
      ctaPrimary: 'Pruébalo gratis', ctaSecondary: 'Ver cómo funciona',
      stat1Value: '60 s', stat1Label: 'Tiempo típico de adaptación',
      stat2Value: '0 $', stat2Label: 'Para empezar',
      stat3Label: 'Idiomas disponibles',
      heroImgAlt: 'Persona trabajando con confianza en una laptop',
      problemLabel: 'El problema',
      problemTitle: 'Calificado. Con experiencia. Y aun así filtrado.',
      problemDesc: 'Casi nunca se trata de tus habilidades. Los sistemas de seguimiento de candidatos (ATS) buscan palabras clave y una estructura específicas — y un currículum que no habla el idioma exacto de la oferta de empleo a menudo nunca llega a una persona.',
      beforeLabel: 'Ejemplo — antes',
      beforeDesc: 'Currículum genérico, igual para cada solicitud — sin los términos exactos que este puesto está buscando.',
      afterLabel: 'Ejemplo — después de Resemy',
      afterDesc: 'La misma experiencia real, reescrita en el propio lenguaje de la oferta de empleo — nada inventado, solo traducido.',
      howLabel: 'Cómo funciona', howTitle: 'Listo en aproximadamente un minuto',
      step1Title: 'Sube tu currículum', step1Desc: 'Un PDF, un DOCX, o simplemente pega el texto — lo que ya tengas.',
      step2Title: 'Pega la oferta de empleo', step2Desc: 'La descripción completa del puesto, para que Resemy sepa exactamente qué debe igualar.',
      step3Title: 'Descarga, ya adaptado', step3Desc: 'Un currículum reescrito, tu puntuación ATS y de reclutador, y qué hacer a continuación.',
      featuresLabel: 'Todo incluido', featuresTitle: 'Mucho más que una simple reescritura',
      feature1Title: 'Currículum adaptado', feature1Desc: 'Reescrito para coincidir con este puesto específico — nunca con experiencia inventada.',
      feature2Title: 'Carta de presentación y correo', feature2Desc: 'Una carta de presentación a juego y un breve correo de solicitud, generados juntos.',
      feature3Title: 'Borradores de cartas de recomendación', feature3Desc: 'Un borrador inicial para que tus referencias lo personalicen y lo firmen.',
      feature4Title: 'Preparación para la entrevista', feature4Desc: 'Preguntas probables, escenarios con el método STAR, y qué preguntas hacer tú.',
      feature5Title: 'Puntuación honesta', feature5Desc: 'Observa tu verdadera comparación antes y después — y lo que realmente aún falta.',
      feature6Title: 'También para reclutadores', feature6Desc: 'Evalúa candidatos frente a una oferta de empleo en segundos con nuestra herramienta de RR. HH.',
      finalTitle: 'Deja de ser filtrado.', finalSub: 'Gratis para empezar. No se requiere tarjeta de crédito.', finalCta: 'Comenzar gratis',
      globalTitle: 'Hecho en Canadá. Creado para el mundo.',
      globalSub: 'Ya sea que estés postulando cerca de casa o al otro lado del mundo, Resemy funciona de la misma forma honesta para todos — sin importar hacia dónde te dirijas después.',
      recruitersTitle: 'Filtrar currículums no debería tomar todo el día.',
      recruitersSub: 'Resemy evalúa a cada candidato frente al puesto que estás contratando, para que dediques menos tiempo a leer currículums y más tiempo a hablar con las personas adecuadas.',
    },
        about: {
      label: 'Sobre nosotros', title: 'Sobre Resemy',
      p1: 'Resemy Solutions es una empresa nueva, registrada en Columbia Británica, Canadá. Empezamos al notar un patrón recurrente en la búsqueda de empleo: los candidatos capacitados llenan su currículum de palabras clave que no pueden respaldar para superar el ATS, o no lo adaptan en absoluto y terminan siendo filtrados de todos modos. Ninguna de las dos opciones funciona.',
      p2: 'Resemy, nuestro primer producto, adopta un enfoque distinto. Reescribe tu currículum para que coincida genuinamente con una oferta de empleo — usando tu experiencia real, reformulada y reorganizada según lo que la oferta realmente pide — sin inventar jamás una habilidad, un empleador o un logro que no sea tuyo. Puedes verlo funcionar: tu puntuación de coincidencia mejora, de forma honesta, desde tu currículum original hasta la versión adaptada.',
      p3: 'Este es nuestro punto de partida, no la meta final — estamos construyendo activamente el siguiente conjunto de herramientas bajo el mismo principio: ayudarte a mostrar tu experiencia real de la mejor manera posible, nunca una inventada. Si Resemy te ayuda a conseguir una entrevista, nos encantaría saberlo — todavía somos lo bastante pequeños como para que tu opinión moldee lo que construimos después.',
    },
    services: {
      label: 'Nuestros servicios', title: 'Una herramienta, dos lados de la contratación',
      sub: 'Ya sea que estés postulando o contratando, Resemy se basa en el mismo principio honesto: información real, evaluada con claridad.',
      candidatesTitle: 'Para candidatos',
      c1t: 'Reescritura de currículum a medida', c1d: 'Tu currículum, reescrito para coincidir con el lenguaje y los requisitos de una oferta de empleo específica.',
      c2t: 'Puntuación ATS y de reclutador', c2d: 'Una puntuación honesta antes y después, además de exactamente qué palabras clave coinciden o faltan.',
      c3t: 'Cartas de presentación y correos de solicitud', c3d: 'Una carta de presentación a juego y un breve correo de solicitud seguro, generados juntos.',
      c4t: 'Borradores de cartas de recomendación', c4d: 'Un borrador inicial para que una de tus referencias reales lo personalice y lo firme.',
      c5t: 'Preparación para entrevistas', c5d: 'Preguntas probables, ejemplos de respuestas, escenarios con el método STAR, y preguntas inteligentes para hacer tú.',
      hrTitle: 'Para RR. HH. y reclutadores',
      h1t: 'Preselección de candidatos', h1d: 'Sube el currículum de un candidato y una oferta de empleo para obtener una evaluación instantánea y coherente.',
      h2t: 'Análisis de fortalezas y brechas', h2d: 'Requisitos cumplidos, requisitos faltantes, y cualquier cosa que valga la pena verificar antes de una entrevista.',
      h3t: 'Informes de evaluación descargables', h3d: 'Un informe claro en formato .docx, listo para compartir, por cada candidato que evalúes.',
      cta: 'Pruébalo gratis',
    },
    contact: {
      label: 'Contacto', title: 'Ponte en contacto',
      sub: 'Preguntas, comentarios o ideas de colaboración — leemos todos los mensajes.',
      nameLabel: 'Nombre', emailLabel: 'Correo electrónico', messageLabel: 'Mensaje',
      send: 'Enviar mensaje', sending: 'Enviando…',
      sentMsg: 'Gracias — tu mensaje está en camino. Te responderemos pronto.',
      errorGeneric: 'Algo salió mal.',
    },
  },

  pa: {
        nav: { about: 'ਸਾਡੇ ਬਾਰੇ', services: 'ਸੇਵਾਵਾਂ', pricing: 'ਕੀਮਤਾਂ', help: 'ਮਦਦ', contact: 'ਸੰਪਰਕ ਕਰੋ', feedback: 'ਫੀਡਬੈਕ', getStarted: 'ਸ਼ੁਰੂ ਕਰੋ', forRecruiters: 'ਭਰਤੀਕਾਰਾਂ ਲਈ' },
    footer: {
      tagline: 'ਬੌਟਸ ਨੂੰ ਪਾਰ ਕਰੋ। ਸਿੱਧੇ ਮਨੁੱਖਾਂ ਤੱਕ ਪਹੁੰਚੋ।',
      product: 'ਉਤਪਾਦ', services: 'ਸੇਵਾਵਾਂ', pricing: 'ਕੀਮਤਾਂ', tryFree: 'ਮੁਫ਼ਤ ਅਜ਼ਮਾਓ',
      company: 'ਕੰਪਨੀ', about: 'ਸਾਡੇ ਬਾਰੇ', contact: 'ਸੰਪਰਕ ਕਰੋ', terms: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ', privacy: 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ',
      followUs: 'ਸਾਨੂੰ ਫਾਲੋ ਕਰੋ', rights: 'ਸਾਰੇ ਅਧਿਕਾਰ ਰਾਖਵੇਂ ਹਨ।',
    },
    home: {
      badge: 'AI ਦੁਆਰਾ ਰੈਜ਼ਿਊਮੇ ਢਾਲਣਾ',
      headline1: 'ਹੋ ਸਕਦਾ ਹੈ ਤੁਹਾਡਾ ਰੈਜ਼ਿਊਮੇ ਰੱਦ ਹੋ ਰਿਹਾ ਹੋਵੇ',
      headline2: 'ਇਸ ਤੋਂ ਪਹਿਲਾਂ ਕਿ ਕੋਈ ਮਨੁੱਖ ਇਸਨੂੰ ਪੜ੍ਹੇ।',
      sub: 'ਜ਼ਿਆਦਾਤਰ ਦਰਮਿਆਨੇ ਅਤੇ ਵੱਡੇ ਰੁਜ਼ਗਾਰਦਾਤਾ ਭਰਤੀਕਾਰ ਦੇ ਖੋਲ੍ਹਣ ਤੋਂ ਪਹਿਲਾਂ ATS ਸਾਫਟਵੇਅਰ ਨਾਲ ਅਰਜ਼ੀਆਂ ਨੂੰ ਫਿਲਟਰ ਕਰਦੇ ਹਨ। Resemy ਤੁਹਾਡੇ ਰੈਜ਼ਿਊਮੇ ਨੂੰ ਇਸ ਵਿੱਚੋਂ ਲੰਘਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਦਾ ਹੈ — ਅਤੇ ਤੁਹਾਨੂੰ ਸਕੋਰ ਦਿਖਾਉਂਦਾ ਹੈ, ਪਹਿਲਾਂ ਅਤੇ ਬਾਅਦ ਵਿੱਚ।',
      ctaPrimary: 'ਮੁਫ਼ਤ ਅਜ਼ਮਾਓ', ctaSecondary: 'ਦੇਖੋ ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
      stat1Value: '60 ਸਕਿੰਟ', stat1Label: 'ਆਮ ਢਾਲਣ ਦਾ ਸਮਾਂ',
      stat2Value: '$0', stat2Label: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ',
      stat3Label: 'ਸਮਰਥਿਤ ਭਾਸ਼ਾਵਾਂ',
      heroImgAlt: "ਇੱਕ ਵਿਅਕਤੀ ਭਰੋਸੇ ਨਾਲ ਲੈਪਟਾਪ 'ਤੇ ਕੰਮ ਕਰ ਰਿਹਾ ਹੈ",
      problemLabel: 'ਸਮੱਸਿਆ',
      problemTitle: 'ਯੋਗ। ਤਜਰਬੇਕਾਰ। ਫਿਰ ਵੀ ਫਿਲਟਰ ਹੋ ਰਹੇ ਹੋ।',
      problemDesc: 'ਇਹ ਬਹੁਤ ਘੱਟ ਹੀ ਤੁਹਾਡੇ ਹੁਨਰਾਂ ਬਾਰੇ ਹੁੰਦਾ ਹੈ। ਅਰਜ਼ੀ ਟਰੈਕਿੰਗ ਸਿਸਟਮ (ATS) ਖਾਸ ਕੀਵਰਡਾਂ ਅਤੇ ਢਾਂਚੇ ਦੀ ਖੋਜ ਕਰਦੇ ਹਨ — ਅਤੇ ਇੱਕ ਰੈਜ਼ਿਊਮੇ ਜੋ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਦੀ ਸਹੀ ਭਾਸ਼ਾ ਨਹੀਂ ਬੋਲਦਾ, ਅਕਸਰ ਕਿਸੇ ਵਿਅਕਤੀ ਤੱਕ ਪਹੁੰਚਦਾ ਹੀ ਨਹੀਂ।',
      beforeLabel: 'ਉਦਾਹਰਣ — ਪਹਿਲਾਂ',
      beforeDesc: 'ਆਮ ਰੈਜ਼ਿਊਮੇ, ਹਰ ਅਰਜ਼ੀ ਲਈ ਇੱਕੋ ਜਿਹਾ — ਉਹਨਾਂ ਸਹੀ ਸ਼ਬਦਾਂ ਦੀ ਘਾਟ ਜੋ ਇਹ ਨੌਕਰੀ ਲੱਭ ਰਹੀ ਹੈ।',
      afterLabel: 'ਉਦਾਹਰਣ — Resemy ਤੋਂ ਬਾਅਦ',
      afterDesc: 'ਉਹੀ ਅਸਲੀ ਤਜਰਬਾ, ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਦੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦੁਬਾਰਾ ਲਿਖਿਆ ਗਿਆ — ਕੁਝ ਵੀ ਘੜਿਆ ਨਹੀਂ ਗਿਆ, ਸਿਰਫ਼ ਢਾਲਿਆ ਗਿਆ।',
      howLabel: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', howTitle: 'ਲਗਭਗ ਇੱਕ ਮਿੰਟ ਵਿੱਚ ਤਿਆਰ',
      step1Title: 'ਆਪਣਾ ਰੈਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ', step1Desc: 'ਇੱਕ PDF, ਇੱਕ DOCX, ਜਾਂ ਸਿਰਫ਼ ਟੈਕਸਟ ਪੇਸਟ ਕਰੋ — ਜੋ ਵੀ ਤੁਹਾਡੇ ਕੋਲ ਪਹਿਲਾਂ ਤੋਂ ਹੈ।',
      step2Title: 'ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਪੇਸਟ ਕਰੋ', step2Desc: 'ਪੂਰਾ ਨੌਕਰੀ ਵੇਰਵਾ, ਤਾਂ ਜੋ Resemy ਨੂੰ ਪਤਾ ਹੋਵੇ ਕਿ ਬਿਲਕੁਲ ਕੀ ਮੇਲ ਕਰਨਾ ਹੈ।',
      step3Title: 'ਡਾਊਨਲੋਡ ਕਰੋ, ਪੂਰੀ ਤਰ੍ਹਾਂ ਢਾਲਿਆ ਹੋਇਆ', step3Desc: 'ਇੱਕ ਦੁਬਾਰਾ ਲਿਖਿਆ ਰੈਜ਼ਿਊਮੇ, ਤੁਹਾਡਾ ATS ਅਤੇ ਮੈਨੇਜਰ ਸਕੋਰ, ਅਤੇ ਅੱਗੇ ਕੀ ਕਰਨਾ ਹੈ।',
      featuresLabel: 'ਸਭ ਕੁਝ ਸ਼ਾਮਲ ਹੈ', featuresTitle: 'ਸਿਰਫ਼ ਦੁਬਾਰਾ ਲਿਖਣ ਤੋਂ ਕਿਤੇ ਵੱਧ',
      feature1Title: 'ਢਾਲਿਆ ਹੋਇਆ ਰੈਜ਼ਿਊਮੇ', feature1Desc: 'ਇਸ ਖਾਸ ਨੌਕਰੀ ਨਾਲ ਮੇਲ ਖਾਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਿਆ ਗਿਆ — ਕਦੇ ਵੀ ਘੜਿਆ ਹੋਇਆ ਤਜਰਬਾ ਨਹੀਂ।',
      feature2Title: 'ਕਵਰ ਲੈਟਰ ਅਤੇ ਈਮੇਲ', feature2Desc: 'ਇੱਕ ਮੇਲ ਖਾਂਦਾ ਕਵਰ ਲੈਟਰ ਅਤੇ ਇੱਕ ਛੋਟੀ ਅਰਜ਼ੀ ਈਮੇਲ, ਇਕੱਠੇ ਤਿਆਰ ਕੀਤੇ ਗਏ।',
      feature3Title: 'ਸਿਫ਼ਾਰਸ਼ੀ ਪੱਤਰ ਦੇ ਖਰੜੇ', feature3Desc: 'ਤੁਹਾਡੇ ਸਿਫ਼ਾਰਸ਼ਕਰਤਾਵਾਂ ਲਈ ਇੱਕ ਸ਼ੁਰੂਆਤੀ ਖਰੜਾ ਜਿਸਨੂੰ ਉਹ ਆਪਣੇ ਮੁਤਾਬਕ ਢਾਲ ਕੇ ਦਸਤਖਤ ਕਰ ਸਕਦੇ ਹਨ।',
      feature4Title: 'ਇੰਟਰਵਿਊ ਦੀ ਤਿਆਰੀ', feature4Desc: 'ਸੰਭਾਵਿਤ ਸਵਾਲ, STAR-ਵਿਧੀ ਦ੍ਰਿਸ਼, ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਪੁੱਛਣ ਲਈ ਸਵਾਲ।',
      feature5Title: 'ਇਮਾਨਦਾਰ ਸਕੋਰਿੰਗ', feature5Desc: 'ਆਪਣਾ ਅਸਲੀ ਪਹਿਲਾਂ-ਅਤੇ-ਬਾਅਦ ਦਾ ਮੇਲ ਦੇਖੋ — ਅਤੇ ਅਸਲ ਵਿੱਚ ਕੀ ਅਜੇ ਵੀ ਗਾਇਬ ਹੈ।',
      feature6Title: 'ਭਰਤੀਕਾਰਾਂ ਲਈ ਵੀ', feature6Desc: 'ਸਾਡੇ HR ਟੂਲ ਨਾਲ ਸਕਿੰਟਾਂ ਵਿੱਚ ਇੱਕ ਪੋਸਟਿੰਗ ਦੇ ਮੁਕਾਬਲੇ ਉਮੀਦਵਾਰਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।',
      finalTitle: 'ਫਿਲਟਰ ਹੋਣਾ ਬੰਦ ਕਰੋ।', finalSub: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਮੁਫ਼ਤ। ਕਿਸੇ ਕ੍ਰੈਡਿਟ ਕਾਰਡ ਦੀ ਲੋੜ ਨਹੀਂ।', finalCta: 'ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
      globalTitle: 'ਕੈਨੇਡਾ ਵਿੱਚ ਬਣਾਇਆ। ਪੂਰੀ ਦੁਨੀਆ ਲਈ ਤਿਆਰ ਕੀਤਾ।',
      globalSub: 'ਭਾਵੇਂ ਤੁਸੀਂ ਆਪਣੇ ਨੇੜੇ ਅਰਜ਼ੀ ਦੇ ਰਹੇ ਹੋ ਜਾਂ ਦੁਨੀਆ ਦੇ ਦੂਜੇ ਪਾਸੇ, Resemy ਹਰ ਕਿਸੇ ਲਈ ਉਸੇ ਇਮਾਨਦਾਰ ਤਰੀਕੇ ਨਾਲ ਕੰਮ ਕਰਦਾ ਹੈ — ਭਾਵੇਂ ਤੁਸੀਂ ਅੱਗੇ ਕਿਤੇ ਵੀ ਜਾ ਰਹੇ ਹੋਵੋ।',
      recruitersTitle: 'ਰੈਜ਼ਿਊਮੇ ਛਾਂਟਣ ਵਿੱਚ ਪੂਰਾ ਦਿਨ ਨਹੀਂ ਲੱਗਣਾ ਚਾਹੀਦਾ।',
      recruitersSub: 'Resemy ਹਰ ਉਮੀਦਵਾਰ ਦਾ ਮੁਲਾਂਕਣ ਉਸ ਨੌਕਰੀ ਦੇ ਮੁਕਾਬਲੇ ਕਰਦਾ ਹੈ ਜਿਸ ਲਈ ਤੁਸੀਂ ਭਰਤੀ ਕਰ ਰਹੇ ਹੋ — ਤਾਂ ਜੋ ਤੁਸੀਂ ਰੈਜ਼ਿਊਮੇ ਪੜ੍ਹਨ ਵਿੱਚ ਘੱਟ ਸਮਾਂ ਅਤੇ ਸਹੀ ਲੋਕਾਂ ਨਾਲ ਗੱਲ ਕਰਨ ਵਿੱਚ ਵੱਧ ਸਮਾਂ ਬਿਤਾਓ।',
    },
        about: {
      label: 'ਸਾਡੇ ਬਾਰੇ', title: 'Resemy ਬਾਰੇ',
      p1: "Resemy Solutions ਇੱਕ ਨਵੀਂ ਕੰਪਨੀ ਹੈ, ਜੋ ਬ੍ਰਿਟਿਸ਼ ਕੋਲੰਬੀਆ, ਕੈਨੇਡਾ ਵਿੱਚ ਰਜਿਸਟਰਡ ਹੈ। ਅਸੀਂ ਨੌਕਰੀ ਦੀ ਭਾਲ ਵਿੱਚ ਇੱਕ ਦੁਹਰਾਈ ਜਾਂਦੀ ਸਮੱਸਿਆ ਦੇਖ ਕੇ ਸ਼ੁਰੂਆਤ ਕੀਤੀ: ਯੋਗ ਉਮੀਦਵਾਰ ਜਾਂ ਤਾਂ ATS ਨੂੰ ਪਾਰ ਕਰਨ ਲਈ ਆਪਣੇ ਰੈਜ਼ਿਊਮੇ ਵਿੱਚ ਅਜਿਹੇ ਕੀਵਰਡ ਭਰ ਦਿੰਦੇ ਹਨ ਜਿਨ੍ਹਾਂ ਦੀ ਉਹਨਾਂ ਕੋਲ ਅਸਲ ਵਿੱਚ ਕੋਈ ਪੁਸ਼ਟੀ ਨਹੀਂ ਹੁੰਦੀ, ਜਾਂ ਬਿਲਕੁਲ ਵੀ ਢਾਲਦੇ ਨਹੀਂ ਅਤੇ ਫਿਰ ਵੀ ਫਿਲਟਰ ਹੋ ਜਾਂਦੇ ਹਨ। ਦੋਵੇਂ ਤਰੀਕੇ ਕੰਮ ਨਹੀਂ ਕਰਦੇ।",
      p2: "Resemy, ਸਾਡਾ ਪਹਿਲਾ ਉਤਪਾਦ, ਇੱਕ ਵੱਖਰਾ ਤਰੀਕਾ ਅਪਣਾਉਂਦਾ ਹੈ। ਇਹ ਤੁਹਾਡੇ ਰੈਜ਼ਿਊਮੇ ਨੂੰ ਸੱਚਮੁੱਚ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਨਾਲ ਮੇਲ ਖਾਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਦਾ ਹੈ — ਤੁਹਾਡੇ ਅਸਲ ਤਜਰਬੇ ਨੂੰ ਵਰਤਦੇ ਹੋਏ, ਪੋਸਟਿੰਗ ਦੀਆਂ ਅਸਲ ਲੋੜਾਂ ਮੁਤਾਬਕ ਮੁੜ-ਸ਼ਬਦਬੱਧ ਅਤੇ ਮੁੜ-ਵਿਵਸਥਿਤ ਕਰਕੇ — ਬਿਨਾਂ ਕਿਸੇ ਅਜਿਹੇ ਹੁਨਰ, ਰੁਜ਼ਗਾਰਦਾਤਾ, ਜਾਂ ਪ੍ਰਾਪਤੀ ਨੂੰ ਘੜੇ ਜੋ ਤੁਹਾਡੀ ਨਹੀਂ ਹੈ। ਤੁਸੀਂ ਇਸਨੂੰ ਕੰਮ ਕਰਦੇ ਦੇਖ ਸਕਦੇ ਹੋ: ਤੁਹਾਡਾ ਮੇਲ ਸਕੋਰ ਤੁਹਾਡੇ ਅਸਲੀ ਰੈਜ਼ਿਊਮੇ ਤੋਂ ਢਾਲੇ ਹੋਏ ਸੰਸਕਰਣ ਤੱਕ, ਇਮਾਨਦਾਰੀ ਨਾਲ ਸੁਧਰਦਾ ਹੈ।",
      p3: "ਇਹ ਸਾਡੀ ਸ਼ੁਰੂਆਤ ਹੈ, ਅੰਤ ਨਹੀਂ — ਅਸੀਂ ਉਸੇ ਸਿਧਾਂਤ 'ਤੇ ਅਧਾਰਿਤ ਅਗਲੇ ਟੂਲਾਂ ਦਾ ਸੈੱਟ ਸਰਗਰਮੀ ਨਾਲ ਬਣਾ ਰਹੇ ਹਾਂ: ਤੁਹਾਨੂੰ ਤੁਹਾਡੇ ਅਸਲ ਤਜਰਬੇ ਨੂੰ ਸਭ ਤੋਂ ਵਧੀਆ ਢੰਗ ਨਾਲ ਪੇਸ਼ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਨਾ, ਕਦੇ ਵੀ ਘੜਿਆ ਹੋਇਆ ਨਹੀਂ। ਜੇ Resemy ਤੁਹਾਨੂੰ ਇੰਟਰਵਿਊ ਦਿਵਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ, ਤਾਂ ਅਸੀਂ ਇਹ ਸੁਣ ਕੇ ਖੁਸ਼ ਹੋਵਾਂਗੇ — ਅਸੀਂ ਹਾਲੇ ਇੰਨੇ ਛੋਟੇ ਹਾਂ ਕਿ ਤੁਹਾਡੀ ਫੀਡਬੈਕ ਇਹ ਤੈਅ ਕਰਦੀ ਹੈ ਕਿ ਅਸੀਂ ਅੱਗੇ ਕੀ ਬਣਾਵਾਂਗੇ।",
    },
    services: {
      label: 'ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ', title: 'ਇੱਕ ਟੂਲ, ਭਰਤੀ ਦੇ ਦੋ ਪਾਸੇ',
      sub: "ਭਾਵੇਂ ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਰਹੇ ਹੋ ਜਾਂ ਭਰਤੀ ਕਰ ਰਹੇ ਹੋ, Resemy ਉਸੇ ਇਮਾਨਦਾਰ ਸਿਧਾਂਤ 'ਤੇ ਬਣਾਇਆ ਗਿਆ ਹੈ: ਅਸਲ ਜਾਣਕਾਰੀ, ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਸਕੋਰ ਕੀਤੀ ਗਈ।",
      candidatesTitle: 'ਉਮੀਦਵਾਰਾਂ ਲਈ',
      c1t: 'ਢਾਲੀ ਹੋਈ ਰੈਜ਼ਿਊਮੇ ਦੁਬਾਰਾ-ਲਿਖਤ', c1d: 'ਤੁਹਾਡਾ ਰੈਜ਼ਿਊਮੇ, ਇੱਕ ਖਾਸ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਦੀ ਭਾਸ਼ਾ ਅਤੇ ਲੋੜਾਂ ਨਾਲ ਮੇਲ ਖਾਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਿਆ ਗਿਆ।',
      c2t: 'ATS ਅਤੇ ਮੈਨੇਜਰ ਸਕੋਰਿੰਗ', c2d: 'ਇੱਕ ਇਮਾਨਦਾਰ ਪਹਿਲਾਂ-ਅਤੇ-ਬਾਅਦ ਦਾ ਸਕੋਰ, ਨਾਲ ਹੀ ਬਿਲਕੁਲ ਕਿਹੜੇ ਕੀਵਰਡ ਮੇਲ ਖਾਂਦੇ ਹਨ ਜਾਂ ਗੁੰਮ ਹਨ।',
      c3t: 'ਕਵਰ ਲੈਟਰ ਅਤੇ ਅਰਜ਼ੀ ਈਮੇਲਾਂ', c3d: 'ਇੱਕ ਮੇਲ ਖਾਂਦਾ ਕਵਰ ਲੈਟਰ ਅਤੇ ਇੱਕ ਛੋਟੀ, ਭਰੋਸੇਮੰਦ ਅਰਜ਼ੀ ਈਮੇਲ, ਇਕੱਠੇ ਤਿਆਰ ਕੀਤੇ ਗਏ।',
      c4t: 'ਸਿਫ਼ਾਰਸ਼ੀ ਪੱਤਰ ਦੇ ਖਰੜੇ', c4d: 'ਤੁਹਾਡੇ ਕਿਸੇ ਅਸਲ ਸਿਫ਼ਾਰਸ਼ਕਰਤਾ ਲਈ ਇੱਕ ਸ਼ੁਰੂਆਤੀ ਖਰੜਾ ਜਿਸਨੂੰ ਉਹ ਆਪਣੇ ਮੁਤਾਬਕ ਢਾਲ ਕੇ ਦਸਤਖਤ ਕਰ ਸਕਦੇ ਹਨ।',
      c5t: 'ਇੰਟਰਵਿਊ ਦੀ ਤਿਆਰੀ', c5d: 'ਸੰਭਾਵਿਤ ਸਵਾਲ, ਉਦਾਹਰਣ ਜਵਾਬ, STAR-ਵਿਧੀ ਦ੍ਰਿਸ਼, ਅਤੇ ਪੁੱਛਣ ਲਈ ਸਮਝਦਾਰ ਸਵਾਲ।',
      hrTitle: 'HR ਅਤੇ ਭਰਤੀਕਾਰਾਂ ਲਈ',
      h1t: 'ਉਮੀਦਵਾਰ ਜਾਂਚ', h1d: 'ਤੁਰੰਤ ਅਤੇ ਇਕਸਾਰ ਮੁਲਾਂਕਣ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਇੱਕ ਉਮੀਦਵਾਰ ਦਾ ਰੈਜ਼ਿਊਮੇ ਅਤੇ ਇੱਕ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਅੱਪਲੋਡ ਕਰੋ।',
      h2t: 'ਤਾਕਤਾਂ ਅਤੇ ਕਮੀਆਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ', h2d: 'ਮੇਲ ਖਾਂਦੀਆਂ ਲੋੜਾਂ, ਗੁੰਮ ਲੋੜਾਂ, ਅਤੇ ਇੰਟਰਵਿਊ ਤੋਂ ਪਹਿਲਾਂ ਜਾਂਚਣ ਯੋਗ ਕੋਈ ਵੀ ਚੀਜ਼।',
      h3t: 'ਡਾਊਨਲੋਡ ਹੋਣ ਯੋਗ ਮੁਲਾਂਕਣ ਰਿਪੋਰਟਾਂ', h3d: 'ਤੁਹਾਡੇ ਵੱਲੋਂ ਜਾਂਚੇ ਗਏ ਹਰ ਉਮੀਦਵਾਰ ਲਈ ਇੱਕ ਸਾਫ਼, ਸਾਂਝਾ ਕਰਨ ਯੋਗ .docx ਰਿਪੋਰਟ।',
      cta: 'ਮੁਫ਼ਤ ਅਜ਼ਮਾਓ',
    },
    contact: {
      label: 'ਸੰਪਰਕ ਕਰੋ', title: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
      sub: 'ਸਵਾਲ, ਫੀਡਬੈਕ, ਜਾਂ ਸਾਂਝੇਦਾਰੀ ਦੇ ਵਿਚਾਰ — ਅਸੀਂ ਹਰ ਸੁਨੇਹਾ ਪੜ੍ਹਦੇ ਹਾਂ।',
      nameLabel: 'ਨਾਮ', emailLabel: 'ਈਮੇਲ', messageLabel: 'ਸੁਨੇਹਾ',
      send: 'ਸੁਨੇਹਾ ਭੇਜੋ', sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      sentMsg: 'ਧੰਨਵਾਦ — ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ। ਅਸੀਂ ਜਲਦੀ ਹੀ ਤੁਹਾਨੂੰ ਜਵਾਬ ਦੇਵਾਂਗੇ।',
      errorGeneric: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।',
    },
  },

  zh: {
        nav: { about: '关于我们', services: '我们的服务', pricing: '价格', help: '帮助', contact: '联系我们', feedback: '反馈', getStarted: '立即开始', forRecruiters: '招聘方' },
    footer: {
      tagline: '跳过筛选机器人，直接触达真人招聘者。',
      product: '产品', services: '服务', pricing: '价格', tryFree: '免费试用',
      company: '公司', about: '关于我们', contact: '联系我们', terms: '服务条款', privacy: '隐私政策',
      followUs: '关注我们', rights: '版权所有。',
    },
    home: {
      badge: 'AI 驱动的简历定制',
      headline1: '您的简历可能在被人看到之前',
      headline2: '就已经被拒绝了。',
      sub: '大多数中大型企业在招聘人员打开申请之前，会先用 ATS 软件对其进行筛选。Resemy 会重写您的简历以通过筛选——并在修改前后都为您显示匹配分数。',
      ctaPrimary: '免费试用', ctaSecondary: '了解工作原理',
      stat1Value: '60 秒', stat1Label: '典型定制用时',
      stat2Value: '$0', stat2Label: '免费开始',
      stat3Label: '支持的语言数量',
      heroImgAlt: '一个人自信地在笔记本电脑上工作',
      problemLabel: '问题所在',
      problemTitle: '有资格，有经验，却仍被过滤掉。',
      problemDesc: '这几乎与您的能力无关。求职申请追踪系统（ATS）会扫描特定的关键词和结构——如果简历没有使用招聘信息中的确切措辞，往往根本无法送达任何一位招聘人员手中。',
      beforeLabel: '示例——定制前',
      beforeDesc: '通用简历，每次申请都一样——缺少这份工作正在寻找的确切关键词。',
      afterLabel: '示例——使用 Resemy 后',
      afterDesc: '同样真实的经历，用招聘信息本身的语言重新表述——没有任何虚构，只是换了表达方式。',
      howLabel: '使用流程', howTitle: '大约一分钟即可完成',
      step1Title: '上传您的简历', step1Desc: '一份 PDF、一份 DOCX，或直接粘贴文本——您现有的任何格式都可以。',
      step2Title: '粘贴职位描述', step2Desc: '完整的职位描述，让 Resemy 准确了解需要匹配的内容。',
      step3Title: '下载定制后的简历', step3Desc: '一份重写的简历、您的 ATS 与招聘经理匹配分数，以及接下来该做什么。',
      featuresLabel: '全部包含', featuresTitle: '远不止是重写简历',
      feature1Title: '定制简历', feature1Desc: '针对这个具体职位重写——绝不虚构经历。',
      feature2Title: '求职信与邮件', feature2Desc: '配套的求职信和简短的求职邮件，一并生成。',
      feature3Title: '推荐信初稿', feature3Desc: '为您的推荐人准备的初稿，供其个性化修改并签署。',
      feature4Title: '面试准备', feature4Desc: '可能被问到的问题、STAR 方法情景练习，以及您可以反问的问题。',
      feature5Title: '诚实的评分', feature5Desc: '查看真实的定制前后对比——以及实际仍然缺失的部分。',
      feature6Title: '同样适合招聘人员', feature6Desc: '使用我们的 HR 工具，几秒钟内即可根据职位描述评估候选人。',
      finalTitle: '不要再被系统过滤掉了。', finalSub: '免费开始，无需信用卡。', finalCta: '免费开始',
      globalTitle: '源自加拿大，为全世界而生。',
      globalSub: '无论您是在家门口求职，还是申请远在地球另一端的职位，Resemy 都以同样诚实的方式为每一个人服务——无论您的下一站在哪里。',
      recruitersTitle: '筛选简历不该占用一整天。',
      recruitersSub: 'Resemy 会根据您要招聘的职位对每位候选人进行评估——让您少花时间阅读简历，多花时间与合适的人交流。',
    },
        about: {
      label: '关于我们', title: '关于 Resemy',
      p1: 'Resemy Solutions 是一家新公司，注册于加拿大不列颠哥伦比亚省。我们注意到求职过程中反复出现的一个问题：有能力的候选人要么在简历里堆砌自己无法佐证的关键词以通过 ATS 筛选，要么完全不做定制，结果同样被筛掉。这两种做法都行不通。',
      p2: '我们的第一款产品 Resemy 采取了不同的方式。它会真正根据职位描述重写您的简历——使用您真实的经历，围绕职位实际要求重新表述和组织——绝不虚构您没有的技能、雇主或成就。您可以亲眼看到效果：从原始简历到定制版本，匹配分数会诚实地提升。',
      p3: '这只是我们的起点，而不是终点——我们正在积极开发基于同一原则的下一批工具：帮助您以最真实、最有力的方式展示自己的经历，绝不虚构。如果 Resemy 帮您获得了面试机会，我们很想听您分享——我们现在的规模还小，您的反馈会直接影响我们接下来要打造的东西。',
    },
    services: {
      label: '我们的服务', title: '一个工具，覆盖招聘的两端',
      sub: '无论您是在求职还是在招聘，Resemy 都基于同一个诚实的原则：真实的信息，清晰的评分。',
      candidatesTitle: '面向求职者',
      c1t: '定制简历重写', c1d: '根据特定职位描述的语言和要求，重写您的简历。',
      c2t: 'ATS 与招聘经理评分', c2d: '诚实的定制前后对比分数，以及具体哪些关键词已匹配或仍缺失。',
      c3t: '求职信与求职邮件', c3d: '配套的求职信和简短、自信的求职邮件，一并生成。',
      c4t: '推荐信初稿', c4d: '为您的一位真实推荐人准备的初稿，供其个性化修改并签署。',
      c5t: '面试准备', c5d: '可能被问到的问题、示例回答、STAR 方法情景练习，以及可以反问的有见地的问题。',
      hrTitle: '面向人力资源与招聘人员',
      h1t: '候选人筛选', h1d: '上传候选人的简历和职位描述，即可获得即时且一致的评估。',
      h2t: '优势与差距分析', h2d: '已匹配的要求、缺失的要求，以及面试前值得再次确认的事项。',
      h3t: '可下载的评估报告', h3d: '为您筛选的每一位候选人生成清晰、可分享的 .docx 报告。',
      cta: '免费试用',
    },
    contact: {
      label: '联系我们', title: '联系我们',
      sub: '问题、反馈或合作想法——我们会阅读每一条留言。',
      nameLabel: '姓名', emailLabel: '电子邮箱', messageLabel: '留言内容',
      send: '发送留言', sending: '发送中…',
      sentMsg: '谢谢——您的留言已发送，我们会尽快回复您。',
      errorGeneric: '出现了一些问题。',
    },
  },
}