export const CONTENT = {
  en: {
    nav: { about: 'About Us', services: 'Services', pricing: 'Pricing', help: 'Help', contact: 'Contact', getStarted: 'Get Started' },
    footer: {
      tagline: 'Get past the bots. Get in front of the humans.',
      product: 'Product', services: 'Services', pricing: 'Pricing', tryFree: 'Try it free',
      company: 'Company', about: 'About Us', contact: 'Contact', terms: 'Terms of Service', privacy: 'Privacy Policy',
      followUs: 'Follow us', rights: 'All rights reserved.',
    },
    home: {
      badge: 'AI-powered résumé tailoring',
      headline1: 'Your résumé might be getting rejected',
      headline2: 'before a human ever reads it.',
      sub: "Most mid-size and large employers filter applications with ATS software before a recruiter opens them. Resemy rewrites your résumé to get through — and shows you the score, before and after.",
      ctaPrimary: 'Try it free', ctaSecondary: 'See how it works',
      stat1Value: '60s', stat1Label: 'Typical tailoring time',
      stat2Value: '$0', stat2Label: 'To get started',
      stat3Label: 'Languages supported',
      heroImgAlt: 'Person confidently working on a laptop',
      problemLabel: 'The problem',
      problemTitle: 'Qualified. Experienced. Still getting filtered out.',
      problemDesc: "It's rarely about your skills. Applicant Tracking Systems scan for specific keywords and structure — and a résumé that doesn't speak the job posting's exact language often never reaches a person at all.",
      beforeLabel: 'Example — before',
      beforeDesc: 'Generic résumé, same for every application — missing the exact terms this job is scanning for.',
      afterLabel: 'Example — after Resemy',
      afterDesc: "Same real experience, rewritten in the job posting's own language — nothing invented, just translated.",
      howLabel: 'How it works', howTitle: 'Ready in about a minute',
      step1Title: 'Upload your résumé', step1Desc: 'A PDF, a DOCX, or just paste the text — whatever you already have.',
      step2Title: 'Paste the job posting', step2Desc: 'The full job description, so Resemy knows exactly what to match.',
      step3Title: 'Download, tailored', step3Desc: 'A rewritten résumé, your ATS + Manager score, and what to do next.',
      featuresLabel: 'Everything included', featuresTitle: 'More than just a rewrite',
      feature1Title: 'Tailored résumé', feature1Desc: 'Rewritten to match this specific job — never fabricated experience.',
      feature2Title: 'Cover letter & email', feature2Desc: 'A matching cover letter and a short application email, generated together.',
      feature3Title: 'Reference letter drafts', feature3Desc: 'A starting draft for your references to personalize and sign.',
      feature4Title: 'Interview prep', feature4Desc: 'Likely questions, STAR-method scenarios, and what to ask them back.',
      feature5Title: 'Honest scoring', feature5Desc: "See your real before-and-after match — and what's genuinely still missing.",
      feature6Title: 'For recruiters too', feature6Desc: 'Screen candidates against a posting in seconds with our HR tool.',
      finalTitle: 'Stop getting filtered out.', finalSub: 'Free to start. No credit card required.', finalCta: 'Get Started free',
      globalTitle: 'Made in Canada. Built for the world.',
      globalSub: "Whether you're applying down the street or across the globe, Resemy works the same honest way for everyone — wherever you're headed next.",
    },
    about: {
      label: 'About us', title: 'Why we built Resemy',
      p1: "Somewhere between sending an application and never hearing back, a real, qualified person gets filtered out by software they never even knew was reading their résumé. That gap — between being capable and being seen — is what Resemy exists to close.",
      p2: "We started Resemy because too many strong candidates were being turned away not for lack of skill, but for lack of the exact words a piece of filtering software happened to be looking for. We believed that gap was worth closing — honestly, without ever inventing experience someone doesn't have.",
      p3: "Every rewrite Resemy produces is grounded in what's actually on your résumé — never fabricated achievements, never invented scope. We'd rather show you an honest gap than a dishonest score.",
    },
    services: {
      label: 'Our services', title: 'One tool, two sides of hiring',
      sub: "Whether you're applying or hiring, Resemy is built around the same honest principle: real information, clearly scored.",
      candidatesTitle: 'For Candidates',
      c1t: 'Tailored résumé rewriting', c1d: "Your résumé, rewritten to match a specific job posting's language and requirements.",
      c2t: 'ATS & Manager scoring', c2d: 'An honest before-and-after score, plus exactly which keywords are matched or missing.',
      c3t: 'Cover letters & application emails', c3d: 'A matching cover letter and a short, confident application email — generated together.',
      c4t: 'Reference letter drafts', c4d: "A starting draft for one of your real references to personalize and sign.",
      c5t: 'Interview preparation', c5d: 'Likely questions, example answers, STAR-method scenarios, and smart questions to ask back.',
      hrTitle: 'For HR & Recruiters',
      h1t: 'Candidate screening', h1d: "Upload a candidate's résumé and a job posting to get an instant, consistent evaluation.",
      h2t: 'Strengths & gap analysis', h2d: 'Matched requirements, missing requirements, and anything worth double-checking before an interview.',
      h3t: 'Downloadable assessment reports', h3d: 'A clean, shareable .docx report for every candidate you screen.',
      cta: 'Try it free',
    },
    contact: {
      label: 'Contact', title: 'Get in touch',
      sub: 'Questions, feedback, or partnership ideas — we read every message.',
      nameLabel: 'Name', emailLabel: 'Email', messageLabel: 'Message',
      send: 'Send message', sending: 'Sending…',
      sentMsg: "Thanks — your message is on its way. We'll get back to you soon.",
      errorGeneric: 'Something went wrong.',
    },
  },

  ar: {
    nav: { about: 'من نحن', services: 'خدماتنا', pricing: 'الأسعار', help: 'المساعدة', contact: 'اتصل بنا', getStarted: 'ابدأ الآن' },
    footer: {
      tagline: 'تجاوز برامج الفرز. تواصل مباشرة مع البشر.',
      product: 'المنتج', services: 'الخدمات', pricing: 'الأسعار', tryFree: 'جرّبه مجانًا',
      company: 'الشركة', about: 'من نحن', contact: 'اتصل بنا', terms: 'شروط الخدمة', privacy: 'سياسة الخصوصية',
      followUs: 'تابعنا', rights: 'جميع الحقوق محفوظة.',
    },
    home: {
      badge: 'تخصيص السيرة الذاتية بالذكاء الاصطناعي',
      headline1: 'قد تُرفض سيرتك الذاتية',
      headline2: 'قبل أن يقرأها أي إنسان على الإطلاق.',
      sub: 'تستخدم معظم الشركات المتوسطة والكبيرة برامج تتبع المتقدمين (ATS) لفرز الطلبات قبل أن يفتحها أي مسؤول توظيف. يعيد Resemy كتابة سيرتك الذاتية لتجاوز هذا الفرز — ويعرض لك الدرجة، قبل التعديل وبعده.',
      ctaPrimary: 'جرّبه مجانًا', ctaSecondary: 'شاهد كيف يعمل',
      stat1Value: '60 ثانية', stat1Label: 'الوقت المعتاد للتخصيص',
      stat2Value: '0$', stat2Label: 'للبدء',
      stat3Label: 'لغات مدعومة',
      heroImgAlt: 'شخص يعمل بثقة على حاسوب محمول',
      problemLabel: 'المشكلة',
      problemTitle: 'مؤهل. لديه خبرة. ومع ذلك يُستبعد.',
      problemDesc: 'نادرًا ما يكون الأمر متعلقًا بمهاراتك. تبحث أنظمة تتبع المتقدمين عن كلمات مفتاحية وبنية محددة — والسيرة الذاتية التي لا تستخدم نفس لغة الإعلان الوظيفي غالبًا ما لا تصل إلى أي شخص على الإطلاق.',
      beforeLabel: 'مثال — قبل',
      beforeDesc: 'سيرة ذاتية عامة، متطابقة في كل طلب — تفتقر إلى المصطلحات الدقيقة التي تبحث عنها هذه الوظيفة.',
      afterLabel: 'مثال — بعد استخدام Resemy',
      afterDesc: 'نفس الخبرة الحقيقية، لكن معاد صياغتها بلغة الإعلان الوظيفي نفسها — لا شيء مُختلَق، فقط إعادة صياغة.',
      howLabel: 'كيف يعمل', howTitle: 'جاهز خلال دقيقة تقريبًا',
      step1Title: 'ارفع سيرتك الذاتية', step1Desc: 'ملف PDF أو DOCX، أو الصق النص مباشرة — أيًا كان ما لديك حاليًا.',
      step2Title: 'الصق الإعلان الوظيفي', step2Desc: 'الوصف الوظيفي كاملاً، ليعرف Resemy بالضبط ما يجب مطابقته.',
      step3Title: 'حمّلها، وهي مخصصة بالكامل', step3Desc: 'سيرة ذاتية معاد كتابتها، ودرجتا ATS والمدير، وما يجب فعله بعد ذلك.',
      featuresLabel: 'كل شيء متضمن', featuresTitle: 'أكثر بكثير من مجرد إعادة كتابة',
      feature1Title: 'سيرة ذاتية مخصصة', feature1Desc: 'معاد كتابتها لتناسب هذه الوظيفة تحديدًا — دون أي خبرة مُختلَقة أبدًا.',
      feature2Title: 'خطاب تقديم وبريد إلكتروني', feature2Desc: 'خطاب تقديم متوافق ورسالة تقديم قصيرة، يتم إنشاؤهما معًا.',
      feature3Title: 'مسودات خطابات توصية', feature3Desc: 'مسودة أولية ليقوم أحد مُزكّيك بتخصيصها والتوقيع عليها.',
      feature4Title: 'التحضير للمقابلة', feature4Desc: 'أسئلة متوقعة، وسيناريوهات بطريقة STAR، وأسئلة ذكية لطرحها بدورك.',
      feature5Title: 'تقييم صادق', feature5Desc: 'شاهد مدى التطابق الحقيقي قبل وبعد — وما الذي لا يزال ناقصًا فعليًا.',
      feature6Title: 'ولمسؤول التوظيف أيضًا', feature6Desc: 'قيّم المرشحين مقابل إعلان وظيفي خلال ثوانٍ باستخدام أداتنا الخاصة بالموارد البشرية.',
      finalTitle: 'توقف عن أن تُستبعد.', finalSub: 'مجاني للبدء. لا حاجة إلى بطاقة ائتمان.', finalCta: 'ابدأ مجانًا',
      globalTitle: 'صُنع في كندا، ومصمم للعالم كله.',
      globalSub: 'سواء كنت تتقدم لوظيفة قريبة منك أو في الجهة الأخرى من العالم، يعمل Resemy بنفس الطريقة الصادقة مع الجميع — أينما كانت وجهتك القادمة.',
    },
    about: {
      label: 'من نحن', title: 'لماذا أنشأنا Resemy',
      p1: 'في مكان ما بين إرسال طلب التوظيف وعدم تلقي أي رد، يُستبعد شخص مؤهل فعليًا بواسطة برنامج لم يكن يعلم حتى أنه يقرأ سيرته الذاتية. هذه الفجوة — بين أن تكون كفؤًا وأن تُرى فعلاً — هي ما وُجد Resemy لسدّها.',
      p2: 'أنشأنا Resemy لأن الكثير من المرشحين الأكفاء كانوا يُستبعدون ليس بسبب نقص المهارة، بل بسبب عدم وجود الكلمات الدقيقة التي كان برنامج الفرز يبحث عنها. رأينا أن هذه الفجوة تستحق أن تُسدّ — بصدق، دون اختلاق أي خبرة لا يملكها الشخص.',
      p3: 'كل إعادة كتابة ينتجها Resemy مبنية على ما هو موجود فعليًا في سيرتك الذاتية — لا إنجازات مُختلَقة أبدًا، ولا نطاق عمل مُبالَغ فيه. نُفضّل أن نُظهر لك فجوة صادقة على أن نمنحك درجة غير صادقة.',
    },
    services: {
      label: 'خدماتنا', title: 'أداة واحدة، لوجهي التوظيف',
      sub: 'سواء كنت تتقدم لوظيفة أو توظّف، يقوم Resemy على المبدأ الصادق نفسه: معلومات حقيقية، وتقييم واضح.',
      candidatesTitle: 'للمتقدمين على الوظيفة',
      c1t: 'إعادة كتابة السيرة الذاتية بشكل مخصص', c1d: 'سيرتك الذاتية، معاد كتابتها لتطابق لغة ومتطلبات إعلان وظيفي محدد.',
      c2t: 'تقييم ATS والمدير', c2d: 'درجة صادقة قبل وبعد، بالإضافة إلى الكلمات المفتاحية المتطابقة أو الناقصة بالتحديد.',
      c3t: 'خطابات التقديم ورسائل التقديم', c3d: 'خطاب تقديم متوافق ورسالة تقديم قصيرة وواثقة، يتم إنشاؤهما معًا.',
      c4t: 'مسودات خطابات التوصية', c4d: 'مسودة أولية ليقوم أحد مُزكّيك الحقيقيين بتخصيصها والتوقيع عليها.',
      c5t: 'التحضير للمقابلات', c5d: 'أسئلة متوقعة، وأمثلة على الإجابات، وسيناريوهات بطريقة STAR، وأسئلة ذكية لطرحها بدورك.',
      hrTitle: 'للموارد البشرية ومسؤول التوظيف',
      h1t: 'فحص المرشحين', h1d: 'ارفع سيرة المرشح الذاتية وإعلان وظيفي للحصول على تقييم فوري ومتسق.',
      h2t: 'تحليل نقاط القوة والفجوات', h2d: 'المتطلبات المتوافقة، والمتطلبات الناقصة، وأي أمر يستحق التحقق منه قبل المقابلة.',
      h3t: 'تقارير تقييم قابلة للتحميل', h3d: 'تقرير واضح بصيغة Word، جاهز للمشاركة، لكل مرشح تقيّمه.',
      cta: 'جرّبه مجانًا',
    },
    contact: {
      label: 'اتصل بنا', title: 'تواصل معنا',
      sub: 'أسئلة أو ملاحظات أو أفكار شراكة — نقرأ كل رسالة تصلنا.',
      nameLabel: 'الاسم', emailLabel: 'البريد الإلكتروني', messageLabel: 'الرسالة',
      send: 'إرسال الرسالة', sending: 'جارٍ الإرسال…',
      sentMsg: 'شكرًا لك — رسالتك في طريقها إلينا. سنرد عليك قريبًا.',
      errorGeneric: 'حدث خطأ ما.',
    },
  },

  fr: {
    nav: { about: 'À propos', services: 'Services', pricing: 'Tarifs', help: 'Aide', contact: 'Contact', getStarted: 'Commencer' },
    footer: {
      tagline: 'Passez les bots. Parlez aux humains.',
      product: 'Produit', services: 'Services', pricing: 'Tarifs', tryFree: 'Essayer gratuitement',
      company: 'Entreprise', about: 'À propos', contact: 'Contact', terms: "Conditions d'utilisation", privacy: 'Politique de confidentialité',
      followUs: 'Suivez-nous', rights: 'Tous droits réservés.',
    },
    home: {
      badge: 'Optimisation de CV par IA',
      headline1: 'Votre CV est peut-être rejeté',
      headline2: "avant même qu'un humain ne le lise.",
      sub: "La plupart des moyennes et grandes entreprises filtrent les candidatures avec un logiciel ATS avant qu'un recruteur ne les ouvre. Resemy réécrit votre CV pour passer ce filtre — et vous montre le score, avant et après.",
      ctaPrimary: 'Essayer gratuitement', ctaSecondary: 'Voir comment ça marche',
      stat1Value: '60 s', stat1Label: "Temps moyen d'adaptation",
      stat2Value: '0 $', stat2Label: 'Pour commencer',
      stat3Label: 'Langues disponibles',
      heroImgAlt: 'Personne travaillant avec assurance sur un ordinateur portable',
      problemLabel: 'Le problème',
      problemTitle: 'Qualifié. Expérimenté. Toujours filtré.',
      problemDesc: "Ce n'est presque jamais une question de compétences. Les logiciels de suivi des candidatures (ATS) recherchent des mots-clés précis et une structure particulière — et un CV qui ne parle pas exactement le langage de l'offre d'emploi n'atteint souvent jamais un humain.",
      beforeLabel: 'Exemple — avant',
      beforeDesc: "CV générique, identique pour chaque candidature — sans les termes précis que ce poste recherche.",
      afterLabel: 'Exemple — après Resemy',
      afterDesc: "La même expérience réelle, réécrite dans le langage exact de l'offre d'emploi — rien n'est inventé, tout est reformulé.",
      howLabel: 'Comment ça marche', howTitle: 'Prêt en une minute environ',
      step1Title: 'Téléchargez votre CV', step1Desc: 'Un PDF, un DOCX, ou collez simplement le texte — ce que vous avez déjà.',
      step2Title: "Collez l'offre d'emploi", step2Desc: "La description complète du poste, pour que Resemy sache exactement quoi cibler.",
      step3Title: 'Téléchargez, sur mesure', step3Desc: 'Un CV réécrit, votre score ATS et recruteur, et les prochaines étapes.',
      featuresLabel: 'Tout est inclus', featuresTitle: "Bien plus qu'une simple réécriture",
      feature1Title: 'CV sur mesure', feature1Desc: "Réécrit pour correspondre à ce poste précis — jamais d'expérience inventée.",
      feature2Title: 'Lettre de motivation et e-mail', feature2Desc: "Une lettre de motivation assortie et un court e-mail de candidature, générés ensemble.",
      feature3Title: 'Ébauches de lettres de recommandation', feature3Desc: 'Un premier brouillon que vos références peuvent personnaliser et signer.',
      feature4Title: "Préparation à l'entretien", feature4Desc: "Questions probables, mises en situation selon la méthode STAR, et questions à poser en retour.",
      feature5Title: 'Notation honnête', feature5Desc: "Voyez votre véritable score avant/après — et ce qui manque réellement encore.",
      feature6Title: 'Pour les recruteurs aussi', feature6Desc: "Évaluez des candidats par rapport à une offre en quelques secondes grâce à notre outil RH.",
      finalTitle: 'Ne soyez plus jamais filtré.', finalSub: 'Gratuit pour commencer. Aucune carte bancaire requise.', finalCta: 'Commencer gratuitement',
      globalTitle: 'Conçu au Canada. Fait pour le monde entier.',
      globalSub: "Que vous postuliez tout près de chez vous ou à l'autre bout du monde, Resemy fonctionne de la même façon honnête pour tout le monde — où que vous alliez ensuite.",
    },
    about: {
      label: 'À propos', title: 'Pourquoi nous avons créé Resemy',
      p1: "Entre l'envoi d'une candidature et l'absence de réponse, une personne réellement qualifiée se fait souvent filtrer par un logiciel dont elle ignorait même l'existence. C'est cet écart — entre être compétent et être vu — que Resemy existe pour combler.",
      p2: "Nous avons créé Resemy parce que trop de bons candidats étaient écartés non par manque de compétences, mais par manque des mots précis qu'un logiciel de filtrage recherchait. Nous avons estimé que cet écart valait la peine d'être comblé — honnêtement, sans jamais inventer une expérience que quelqu'un n'a pas.",
      p3: "Chaque réécriture produite par Resemy est fondée sur ce qui figure réellement dans votre CV — jamais de réalisations fabriquées, jamais d'expérience inventée. Nous préférons vous montrer un écart honnête plutôt qu'un score malhonnête.",
    },
    services: {
      label: 'Nos services', title: "Un seul outil, deux facettes du recrutement",
      sub: "Que vous postuliez ou que vous recrutiez, Resemy repose sur le même principe honnête : des informations réelles, clairement évaluées.",
      candidatesTitle: 'Pour les candidats',
      c1t: 'Réécriture de CV sur mesure', c1d: "Votre CV, réécrit pour correspondre au langage et aux exigences d'une offre d'emploi précise.",
      c2t: 'Notation ATS et recruteur', c2d: 'Un score honnête avant/après, ainsi que les mots-clés exacts trouvés ou manquants.',
      c3t: 'Lettres de motivation et e-mails de candidature', c3d: 'Une lettre de motivation assortie et un court e-mail de candidature confiant, générés ensemble.',
      c4t: 'Ébauches de lettres de recommandation', c4d: "Un premier brouillon que l'une de vos références réelles peut personnaliser et signer.",
      c5t: "Préparation à l'entretien", c5d: "Questions probables, exemples de réponses, mises en situation selon la méthode STAR, et questions pertinentes à poser en retour.",
      hrTitle: 'Pour les RH et les recruteurs',
      h1t: 'Présélection des candidats', h1d: "Téléchargez le CV d'un candidat et une offre d'emploi pour obtenir une évaluation instantanée et cohérente.",
      h2t: 'Analyse des forces et des lacunes', h2d: "Exigences satisfaites, exigences manquantes, et tout élément à vérifier avant un entretien.",
      h3t: "Rapports d'évaluation téléchargeables", h3d: "Un rapport clair au format .docx, prêt à partager, pour chaque candidat évalué.",
      cta: 'Essayer gratuitement',
    },
    contact: {
      label: 'Contact', title: 'Contactez-nous',
      sub: "Questions, commentaires ou idées de partenariat — nous lisons chaque message.",
      nameLabel: 'Nom', emailLabel: 'E-mail', messageLabel: 'Message',
      send: 'Envoyer le message', sending: 'Envoi en cours…',
      sentMsg: "Merci — votre message est en route. Nous vous répondrons bientôt.",
      errorGeneric: "Une erreur s'est produite.",
    },
  },

  es: {
    nav: { about: 'Sobre nosotros', services: 'Servicios', pricing: 'Precios', help: 'Ayuda', contact: 'Contacto', getStarted: 'Comenzar' },
    footer: {
      tagline: 'Supera a los robots. Llega a los humanos.',
      product: 'Producto', services: 'Servicios', pricing: 'Precios', tryFree: 'Pruébalo gratis',
      company: 'Empresa', about: 'Sobre nosotros', contact: 'Contacto', terms: 'Términos de servicio', privacy: 'Política de privacidad',
      followUs: 'Síguenos', rights: 'Todos los derechos reservados.',
    },
    home: {
      badge: 'Adaptación de currículums con IA',
      headline1: 'Es posible que tu currículum esté siendo rechazado',
      headline2: 'antes de que un humano lo lea.',
      sub: 'La mayoría de las empresas medianas y grandes filtran las solicitudes con software ATS antes de que un reclutador las abra. Resemy reescribe tu currículum para superar ese filtro, y te muestra la puntuación, antes y después.',
      ctaPrimary: 'Pruébalo gratis', ctaSecondary: 'Ver cómo funciona',
      stat1Value: '60 s', stat1Label: 'Tiempo típico de adaptación',
      stat2Value: '0 $', stat2Label: 'Para empezar',
      stat3Label: 'Idiomas disponibles',
      heroImgAlt: 'Persona trabajando con confianza en una laptop',
      problemLabel: 'El problema',
      problemTitle: 'Calificado. Con experiencia. Y aun así filtrado.',
      problemDesc: 'Casi nunca se trata de tus habilidades. Los sistemas de seguimiento de candidatos (ATS) buscan palabras clave y una estructura específicas — y un currículum que no habla el idioma exacto de la oferta de empleo a menudo nunca llega a una persona.',
      beforeLabel: 'Ejemplo — antes',
      beforeDesc: 'Currículum genérico, igual para cada solicitud — sin los términos exactos que este puesto está buscando.',
      afterLabel: 'Ejemplo — después de Resemy',
      afterDesc: 'La misma experiencia real, reescrita en el propio lenguaje de la oferta de empleo — nada inventado, solo traducido.',
      howLabel: 'Cómo funciona', howTitle: 'Listo en aproximadamente un minuto',
      step1Title: 'Sube tu currículum', step1Desc: 'Un PDF, un DOCX, o simplemente pega el texto — lo que ya tengas.',
      step2Title: 'Pega la oferta de empleo', step2Desc: 'La descripción completa del puesto, para que Resemy sepa exactamente qué debe igualar.',
      step3Title: 'Descarga, ya adaptado', step3Desc: 'Un currículum reescrito, tu puntuación ATS y de reclutador, y qué hacer a continuación.',
      featuresLabel: 'Todo incluido', featuresTitle: 'Mucho más que una simple reescritura',
      feature1Title: 'Currículum adaptado', feature1Desc: 'Reescrito para coincidir con este puesto específico — nunca con experiencia inventada.',
      feature2Title: 'Carta de presentación y correo', feature2Desc: 'Una carta de presentación a juego y un breve correo de solicitud, generados juntos.',
      feature3Title: 'Borradores de cartas de recomendación', feature3Desc: 'Un borrador inicial para que tus referencias lo personalicen y lo firmen.',
      feature4Title: 'Preparación para la entrevista', feature4Desc: 'Preguntas probables, escenarios con el método STAR, y qué preguntas hacer tú.',
      feature5Title: 'Puntuación honesta', feature5Desc: 'Observa tu verdadera comparación antes y después — y lo que realmente aún falta.',
      feature6Title: 'También para reclutadores', feature6Desc: 'Evalúa candidatos frente a una oferta de empleo en segundos con nuestra herramienta de RR. HH.',
      finalTitle: 'Deja de ser filtrado.', finalSub: 'Gratis para empezar. No se requiere tarjeta de crédito.', finalCta: 'Comenzar gratis',
      globalTitle: 'Hecho en Canadá. Creado para el mundo.',
      globalSub: 'Ya sea que estés postulando cerca de casa o al otro lado del mundo, Resemy funciona de la misma forma honesta para todos — sin importar hacia dónde te dirijas después.',
    },
    about: {
      label: 'Sobre nosotros', title: 'Por qué creamos Resemy',
      p1: 'En algún punto entre enviar una solicitud y no volver a saber nada, una persona real y calificada queda filtrada por un software que ni siquiera sabía que estaba leyendo su currículum. Esa brecha — entre ser capaz y ser visto — es lo que Resemy existe para cerrar.',
      p2: 'Creamos Resemy porque demasiados buenos candidatos eran rechazados no por falta de habilidad, sino por falta de las palabras exactas que un software de filtrado estaba buscando. Creímos que valía la pena cerrar esa brecha — de forma honesta, sin inventar jamás una experiencia que alguien no tiene.',
      p3: 'Cada reescritura que produce Resemy se basa en lo que realmente hay en tu currículum — nunca logros inventados, nunca alcance fabricado. Preferimos mostrarte una brecha honesta antes que una puntuación deshonesta.',
    },
    services: {
      label: 'Nuestros servicios', title: 'Una herramienta, dos lados de la contratación',
      sub: 'Ya sea que estés postulando o contratando, Resemy se basa en el mismo principio honesto: información real, evaluada con claridad.',
      candidatesTitle: 'Para candidatos',
      c1t: 'Reescritura de currículum a medida', c1d: 'Tu currículum, reescrito para coincidir con el lenguaje y los requisitos de una oferta de empleo específica.',
      c2t: 'Puntuación ATS y de reclutador', c2d: 'Una puntuación honesta antes y después, además de exactamente qué palabras clave coinciden o faltan.',
      c3t: 'Cartas de presentación y correos de solicitud', c3d: 'Una carta de presentación a juego y un breve correo de solicitud seguro, generados juntos.',
      c4t: 'Borradores de cartas de recomendación', c4d: 'Un borrador inicial para que una de tus referencias reales lo personalice y lo firme.',
      c5t: 'Preparación para entrevistas', c5d: 'Preguntas probables, ejemplos de respuestas, escenarios con el método STAR, y preguntas inteligentes para hacer tú.',
      hrTitle: 'Para RR. HH. y reclutadores',
      h1t: 'Preselección de candidatos', h1d: 'Sube el currículum de un candidato y una oferta de empleo para obtener una evaluación instantánea y coherente.',
      h2t: 'Análisis de fortalezas y brechas', h2d: 'Requisitos cumplidos, requisitos faltantes, y cualquier cosa que valga la pena verificar antes de una entrevista.',
      h3t: 'Informes de evaluación descargables', h3d: 'Un informe claro en formato .docx, listo para compartir, por cada candidato que evalúes.',
      cta: 'Pruébalo gratis',
    },
    contact: {
      label: 'Contacto', title: 'Ponte en contacto',
      sub: 'Preguntas, comentarios o ideas de colaboración — leemos todos los mensajes.',
      nameLabel: 'Nombre', emailLabel: 'Correo electrónico', messageLabel: 'Mensaje',
      send: 'Enviar mensaje', sending: 'Enviando…',
      sentMsg: 'Gracias — tu mensaje está en camino. Te responderemos pronto.',
      errorGeneric: 'Algo salió mal.',
    },
  },

  pa: {
    nav: { about: 'ਸਾਡੇ ਬਾਰੇ', services: 'ਸੇਵਾਵਾਂ', pricing: 'ਕੀਮਤਾਂ', help: 'ਮਦਦ', contact: 'ਸੰਪਰਕ ਕਰੋ', getStarted: 'ਸ਼ੁਰੂ ਕਰੋ' },
    footer: {
      tagline: 'ਬੌਟਸ ਨੂੰ ਪਾਰ ਕਰੋ। ਸਿੱਧੇ ਮਨੁੱਖਾਂ ਤੱਕ ਪਹੁੰਚੋ।',
      product: 'ਉਤਪਾਦ', services: 'ਸੇਵਾਵਾਂ', pricing: 'ਕੀਮਤਾਂ', tryFree: 'ਮੁਫ਼ਤ ਅਜ਼ਮਾਓ',
      company: 'ਕੰਪਨੀ', about: 'ਸਾਡੇ ਬਾਰੇ', contact: 'ਸੰਪਰਕ ਕਰੋ', terms: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ', privacy: 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ',
      followUs: 'ਸਾਨੂੰ ਫਾਲੋ ਕਰੋ', rights: 'ਸਾਰੇ ਅਧਿਕਾਰ ਰਾਖਵੇਂ ਹਨ।',
    },
    home: {
      badge: 'AI ਦੁਆਰਾ ਰੈਜ਼ਿਊਮੇ ਢਾਲਣਾ',
      headline1: 'ਹੋ ਸਕਦਾ ਹੈ ਤੁਹਾਡਾ ਰੈਜ਼ਿਊਮੇ ਰੱਦ ਹੋ ਰਿਹਾ ਹੋਵੇ',
      headline2: 'ਇਸ ਤੋਂ ਪਹਿਲਾਂ ਕਿ ਕੋਈ ਮਨੁੱਖ ਇਸਨੂੰ ਪੜ੍ਹੇ।',
      sub: 'ਜ਼ਿਆਦਾਤਰ ਦਰਮਿਆਨੇ ਅਤੇ ਵੱਡੇ ਰੁਜ਼ਗਾਰਦਾਤਾ ਭਰਤੀਕਾਰ ਦੇ ਖੋਲ੍ਹਣ ਤੋਂ ਪਹਿਲਾਂ ATS ਸਾਫਟਵੇਅਰ ਨਾਲ ਅਰਜ਼ੀਆਂ ਨੂੰ ਫਿਲਟਰ ਕਰਦੇ ਹਨ। Resemy ਤੁਹਾਡੇ ਰੈਜ਼ਿਊਮੇ ਨੂੰ ਇਸ ਵਿੱਚੋਂ ਲੰਘਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਦਾ ਹੈ — ਅਤੇ ਤੁਹਾਨੂੰ ਸਕੋਰ ਦਿਖਾਉਂਦਾ ਹੈ, ਪਹਿਲਾਂ ਅਤੇ ਬਾਅਦ ਵਿੱਚ।',
      ctaPrimary: 'ਮੁਫ਼ਤ ਅਜ਼ਮਾਓ', ctaSecondary: 'ਦੇਖੋ ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
      stat1Value: '60 ਸਕਿੰਟ', stat1Label: 'ਆਮ ਢਾਲਣ ਦਾ ਸਮਾਂ',
      stat2Value: '$0', stat2Label: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ',
      stat3Label: 'ਸਮਰਥਿਤ ਭਾਸ਼ਾਵਾਂ',
      heroImgAlt: "ਇੱਕ ਵਿਅਕਤੀ ਭਰੋਸੇ ਨਾਲ ਲੈਪਟਾਪ 'ਤੇ ਕੰਮ ਕਰ ਰਿਹਾ ਹੈ",
      problemLabel: 'ਸਮੱਸਿਆ',
      problemTitle: 'ਯੋਗ। ਤਜਰਬੇਕਾਰ। ਫਿਰ ਵੀ ਫਿਲਟਰ ਹੋ ਰਹੇ ਹੋ।',
      problemDesc: 'ਇਹ ਬਹੁਤ ਘੱਟ ਹੀ ਤੁਹਾਡੇ ਹੁਨਰਾਂ ਬਾਰੇ ਹੁੰਦਾ ਹੈ। ਅਰਜ਼ੀ ਟਰੈਕਿੰਗ ਸਿਸਟਮ (ATS) ਖਾਸ ਕੀਵਰਡਾਂ ਅਤੇ ਢਾਂਚੇ ਦੀ ਖੋਜ ਕਰਦੇ ਹਨ — ਅਤੇ ਇੱਕ ਰੈਜ਼ਿਊਮੇ ਜੋ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਦੀ ਸਹੀ ਭਾਸ਼ਾ ਨਹੀਂ ਬੋਲਦਾ, ਅਕਸਰ ਕਿਸੇ ਵਿਅਕਤੀ ਤੱਕ ਪਹੁੰਚਦਾ ਹੀ ਨਹੀਂ।',
      beforeLabel: 'ਉਦਾਹਰਣ — ਪਹਿਲਾਂ',
      beforeDesc: 'ਆਮ ਰੈਜ਼ਿਊਮੇ, ਹਰ ਅਰਜ਼ੀ ਲਈ ਇੱਕੋ ਜਿਹਾ — ਉਹਨਾਂ ਸਹੀ ਸ਼ਬਦਾਂ ਦੀ ਘਾਟ ਜੋ ਇਹ ਨੌਕਰੀ ਲੱਭ ਰਹੀ ਹੈ।',
      afterLabel: 'ਉਦਾਹਰਣ — Resemy ਤੋਂ ਬਾਅਦ',
      afterDesc: 'ਉਹੀ ਅਸਲੀ ਤਜਰਬਾ, ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਦੀ ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਦੁਬਾਰਾ ਲਿਖਿਆ ਗਿਆ — ਕੁਝ ਵੀ ਘੜਿਆ ਨਹੀਂ ਗਿਆ, ਸਿਰਫ਼ ਢਾਲਿਆ ਗਿਆ।',
      howLabel: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', howTitle: 'ਲਗਭਗ ਇੱਕ ਮਿੰਟ ਵਿੱਚ ਤਿਆਰ',
      step1Title: 'ਆਪਣਾ ਰੈਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ', step1Desc: 'ਇੱਕ PDF, ਇੱਕ DOCX, ਜਾਂ ਸਿਰਫ਼ ਟੈਕਸਟ ਪੇਸਟ ਕਰੋ — ਜੋ ਵੀ ਤੁਹਾਡੇ ਕੋਲ ਪਹਿਲਾਂ ਤੋਂ ਹੈ।',
      step2Title: 'ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਪੇਸਟ ਕਰੋ', step2Desc: 'ਪੂਰਾ ਨੌਕਰੀ ਵੇਰਵਾ, ਤਾਂ ਜੋ Resemy ਨੂੰ ਪਤਾ ਹੋਵੇ ਕਿ ਬਿਲਕੁਲ ਕੀ ਮੇਲ ਕਰਨਾ ਹੈ।',
      step3Title: 'ਡਾਊਨਲੋਡ ਕਰੋ, ਪੂਰੀ ਤਰ੍ਹਾਂ ਢਾਲਿਆ ਹੋਇਆ', step3Desc: 'ਇੱਕ ਦੁਬਾਰਾ ਲਿਖਿਆ ਰੈਜ਼ਿਊਮੇ, ਤੁਹਾਡਾ ATS ਅਤੇ ਮੈਨੇਜਰ ਸਕੋਰ, ਅਤੇ ਅੱਗੇ ਕੀ ਕਰਨਾ ਹੈ।',
      featuresLabel: 'ਸਭ ਕੁਝ ਸ਼ਾਮਲ ਹੈ', featuresTitle: 'ਸਿਰਫ਼ ਦੁਬਾਰਾ ਲਿਖਣ ਤੋਂ ਕਿਤੇ ਵੱਧ',
      feature1Title: 'ਢਾਲਿਆ ਹੋਇਆ ਰੈਜ਼ਿਊਮੇ', feature1Desc: 'ਇਸ ਖਾਸ ਨੌਕਰੀ ਨਾਲ ਮੇਲ ਖਾਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਿਆ ਗਿਆ — ਕਦੇ ਵੀ ਘੜਿਆ ਹੋਇਆ ਤਜਰਬਾ ਨਹੀਂ।',
      feature2Title: 'ਕਵਰ ਲੈਟਰ ਅਤੇ ਈਮੇਲ', feature2Desc: 'ਇੱਕ ਮੇਲ ਖਾਂਦਾ ਕਵਰ ਲੈਟਰ ਅਤੇ ਇੱਕ ਛੋਟੀ ਅਰਜ਼ੀ ਈਮੇਲ, ਇਕੱਠੇ ਤਿਆਰ ਕੀਤੇ ਗਏ।',
      feature3Title: 'ਸਿਫ਼ਾਰਸ਼ੀ ਪੱਤਰ ਦੇ ਖਰੜੇ', feature3Desc: 'ਤੁਹਾਡੇ ਸਿਫ਼ਾਰਸ਼ਕਰਤਾਵਾਂ ਲਈ ਇੱਕ ਸ਼ੁਰੂਆਤੀ ਖਰੜਾ ਜਿਸਨੂੰ ਉਹ ਆਪਣੇ ਮੁਤਾਬਕ ਢਾਲ ਕੇ ਦਸਤਖਤ ਕਰ ਸਕਦੇ ਹਨ।',
      feature4Title: 'ਇੰਟਰਵਿਊ ਦੀ ਤਿਆਰੀ', feature4Desc: 'ਸੰਭਾਵਿਤ ਸਵਾਲ, STAR-ਵਿਧੀ ਦ੍ਰਿਸ਼, ਅਤੇ ਉਹਨਾਂ ਨੂੰ ਪੁੱਛਣ ਲਈ ਸਵਾਲ।',
      feature5Title: 'ਇਮਾਨਦਾਰ ਸਕੋਰਿੰਗ', feature5Desc: 'ਆਪਣਾ ਅਸਲੀ ਪਹਿਲਾਂ-ਅਤੇ-ਬਾਅਦ ਦਾ ਮੇਲ ਦੇਖੋ — ਅਤੇ ਅਸਲ ਵਿੱਚ ਕੀ ਅਜੇ ਵੀ ਗਾਇਬ ਹੈ।',
      feature6Title: 'ਭਰਤੀਕਾਰਾਂ ਲਈ ਵੀ', feature6Desc: 'ਸਾਡੇ HR ਟੂਲ ਨਾਲ ਸਕਿੰਟਾਂ ਵਿੱਚ ਇੱਕ ਪੋਸਟਿੰਗ ਦੇ ਮੁਕਾਬਲੇ ਉਮੀਦਵਾਰਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।',
      finalTitle: 'ਫਿਲਟਰ ਹੋਣਾ ਬੰਦ ਕਰੋ।', finalSub: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਮੁਫ਼ਤ। ਕਿਸੇ ਕ੍ਰੈਡਿਟ ਕਾਰਡ ਦੀ ਲੋੜ ਨਹੀਂ।', finalCta: 'ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ',
      globalTitle: 'ਕੈਨੇਡਾ ਵਿੱਚ ਬਣਾਇਆ। ਪੂਰੀ ਦੁਨੀਆ ਲਈ ਤਿਆਰ ਕੀਤਾ।',
      globalSub: 'ਭਾਵੇਂ ਤੁਸੀਂ ਆਪਣੇ ਨੇੜੇ ਅਰਜ਼ੀ ਦੇ ਰਹੇ ਹੋ ਜਾਂ ਦੁਨੀਆ ਦੇ ਦੂਜੇ ਪਾਸੇ, Resemy ਹਰ ਕਿਸੇ ਲਈ ਉਸੇ ਇਮਾਨਦਾਰ ਤਰੀਕੇ ਨਾਲ ਕੰਮ ਕਰਦਾ ਹੈ — ਭਾਵੇਂ ਤੁਸੀਂ ਅੱਗੇ ਕਿਤੇ ਵੀ ਜਾ ਰਹੇ ਹੋਵੋ।',
    },
    about: {
      label: 'ਸਾਡੇ ਬਾਰੇ', title: 'ਅਸੀਂ Resemy ਕਿਉਂ ਬਣਾਇਆ',
      p1: 'ਇੱਕ ਅਰਜ਼ੀ ਭੇਜਣ ਅਤੇ ਕਦੇ ਜਵਾਬ ਨਾ ਮਿਲਣ ਦੇ ਵਿਚਕਾਰ ਕਿਤੇ, ਇੱਕ ਅਸਲ, ਯੋਗ ਵਿਅਕਤੀ ਉਸ ਸਾਫਟਵੇਅਰ ਦੁਆਰਾ ਫਿਲਟਰ ਹੋ ਜਾਂਦਾ ਹੈ ਜਿਸ ਬਾਰੇ ਉਹਨਾਂ ਨੂੰ ਇਹ ਵੀ ਨਹੀਂ ਪਤਾ ਸੀ ਕਿ ਇਹ ਉਹਨਾਂ ਦਾ ਰੈਜ਼ਿਊਮੇ ਪੜ੍ਹ ਰਿਹਾ ਸੀ। ਇਹ ਪਾੜਾ — ਯੋਗ ਹੋਣ ਅਤੇ ਦੇਖੇ ਜਾਣ ਦੇ ਵਿਚਕਾਰ — ਉਹ ਹੈ ਜਿਸਨੂੰ ਭਰਨ ਲਈ Resemy ਮੌਜੂਦ ਹੈ।',
      p2: 'ਅਸੀਂ Resemy ਇਸ ਲਈ ਸ਼ੁਰੂ ਕੀਤਾ ਕਿਉਂਕਿ ਬਹੁਤ ਸਾਰੇ ਮਜ਼ਬੂਤ ਉਮੀਦਵਾਰਾਂ ਨੂੰ ਹੁਨਰ ਦੀ ਘਾਟ ਕਾਰਨ ਨਹੀਂ, ਸਗੋਂ ਉਹਨਾਂ ਸਹੀ ਸ਼ਬਦਾਂ ਦੀ ਘਾਟ ਕਾਰਨ ਰੱਦ ਕੀਤਾ ਜਾ ਰਿਹਾ ਸੀ ਜੋ ਇੱਕ ਫਿਲਟਰਿੰਗ ਸਾਫਟਵੇਅਰ ਲੱਭ ਰਿਹਾ ਸੀ। ਸਾਨੂੰ ਲੱਗਿਆ ਕਿ ਇਹ ਪਾੜਾ ਭਰਨ ਯੋਗ ਸੀ — ਇਮਾਨਦਾਰੀ ਨਾਲ, ਕਦੇ ਵੀ ਅਜਿਹਾ ਤਜਰਬਾ ਘੜੇ ਬਿਨਾਂ ਜੋ ਕਿਸੇ ਕੋਲ ਨਹੀਂ ਹੈ।',
      p3: 'Resemy ਦੁਆਰਾ ਤਿਆਰ ਕੀਤੀ ਹਰ ਦੁਬਾਰਾ-ਲਿਖਤ ਤੁਹਾਡੇ ਰੈਜ਼ਿਊਮੇ ਵਿੱਚ ਅਸਲ ਵਿੱਚ ਮੌਜੂਦ ਚੀਜ਼ਾਂ \'ਤੇ ਆਧਾਰਿਤ ਹੁੰਦੀ ਹੈ — ਕਦੇ ਵੀ ਘੜੀਆਂ ਪ੍ਰਾਪਤੀਆਂ ਨਹੀਂ, ਕਦੇ ਵੀ ਘੜਿਆ ਹੋਇਆ ਦਾਇਰਾ ਨਹੀਂ। ਅਸੀਂ ਤੁਹਾਨੂੰ ਇੱਕ ਝੂਠੇ ਸਕੋਰ ਦੀ ਬਜਾਏ ਇੱਕ ਇਮਾਨਦਾਰ ਕਮੀ ਦਿਖਾਉਣੀ ਪਸੰਦ ਕਰਾਂਗੇ।',
    },
    services: {
      label: 'ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ', title: 'ਇੱਕ ਟੂਲ, ਭਰਤੀ ਦੇ ਦੋ ਪਾਸੇ',
      sub: "ਭਾਵੇਂ ਤੁਸੀਂ ਅਰਜ਼ੀ ਦੇ ਰਹੇ ਹੋ ਜਾਂ ਭਰਤੀ ਕਰ ਰਹੇ ਹੋ, Resemy ਉਸੇ ਇਮਾਨਦਾਰ ਸਿਧਾਂਤ 'ਤੇ ਬਣਾਇਆ ਗਿਆ ਹੈ: ਅਸਲ ਜਾਣਕਾਰੀ, ਸਪੱਸ਼ਟ ਤੌਰ 'ਤੇ ਸਕੋਰ ਕੀਤੀ ਗਈ।",
      candidatesTitle: 'ਉਮੀਦਵਾਰਾਂ ਲਈ',
      c1t: 'ਢਾਲੀ ਹੋਈ ਰੈਜ਼ਿਊਮੇ ਦੁਬਾਰਾ-ਲਿਖਤ', c1d: 'ਤੁਹਾਡਾ ਰੈਜ਼ਿਊਮੇ, ਇੱਕ ਖਾਸ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਦੀ ਭਾਸ਼ਾ ਅਤੇ ਲੋੜਾਂ ਨਾਲ ਮੇਲ ਖਾਣ ਲਈ ਦੁਬਾਰਾ ਲਿਖਿਆ ਗਿਆ।',
      c2t: 'ATS ਅਤੇ ਮੈਨੇਜਰ ਸਕੋਰਿੰਗ', c2d: 'ਇੱਕ ਇਮਾਨਦਾਰ ਪਹਿਲਾਂ-ਅਤੇ-ਬਾਅਦ ਦਾ ਸਕੋਰ, ਨਾਲ ਹੀ ਬਿਲਕੁਲ ਕਿਹੜੇ ਕੀਵਰਡ ਮੇਲ ਖਾਂਦੇ ਹਨ ਜਾਂ ਗੁੰਮ ਹਨ।',
      c3t: 'ਕਵਰ ਲੈਟਰ ਅਤੇ ਅਰਜ਼ੀ ਈਮੇਲਾਂ', c3d: 'ਇੱਕ ਮੇਲ ਖਾਂਦਾ ਕਵਰ ਲੈਟਰ ਅਤੇ ਇੱਕ ਛੋਟੀ, ਭਰੋਸੇਮੰਦ ਅਰਜ਼ੀ ਈਮੇਲ, ਇਕੱਠੇ ਤਿਆਰ ਕੀਤੇ ਗਏ।',
      c4t: 'ਸਿਫ਼ਾਰਸ਼ੀ ਪੱਤਰ ਦੇ ਖਰੜੇ', c4d: 'ਤੁਹਾਡੇ ਕਿਸੇ ਅਸਲ ਸਿਫ਼ਾਰਸ਼ਕਰਤਾ ਲਈ ਇੱਕ ਸ਼ੁਰੂਆਤੀ ਖਰੜਾ ਜਿਸਨੂੰ ਉਹ ਆਪਣੇ ਮੁਤਾਬਕ ਢਾਲ ਕੇ ਦਸਤਖਤ ਕਰ ਸਕਦੇ ਹਨ।',
      c5t: 'ਇੰਟਰਵਿਊ ਦੀ ਤਿਆਰੀ', c5d: 'ਸੰਭਾਵਿਤ ਸਵਾਲ, ਉਦਾਹਰਣ ਜਵਾਬ, STAR-ਵਿਧੀ ਦ੍ਰਿਸ਼, ਅਤੇ ਪੁੱਛਣ ਲਈ ਸਮਝਦਾਰ ਸਵਾਲ।',
      hrTitle: 'HR ਅਤੇ ਭਰਤੀਕਾਰਾਂ ਲਈ',
      h1t: 'ਉਮੀਦਵਾਰ ਜਾਂਚ', h1d: 'ਤੁਰੰਤ ਅਤੇ ਇਕਸਾਰ ਮੁਲਾਂਕਣ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਇੱਕ ਉਮੀਦਵਾਰ ਦਾ ਰੈਜ਼ਿਊਮੇ ਅਤੇ ਇੱਕ ਨੌਕਰੀ ਦੀ ਪੋਸਟਿੰਗ ਅੱਪਲੋਡ ਕਰੋ।',
      h2t: 'ਤਾਕਤਾਂ ਅਤੇ ਕਮੀਆਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ', h2d: 'ਮੇਲ ਖਾਂਦੀਆਂ ਲੋੜਾਂ, ਗੁੰਮ ਲੋੜਾਂ, ਅਤੇ ਇੰਟਰਵਿਊ ਤੋਂ ਪਹਿਲਾਂ ਜਾਂਚਣ ਯੋਗ ਕੋਈ ਵੀ ਚੀਜ਼।',
      h3t: 'ਡਾਊਨਲੋਡ ਹੋਣ ਯੋਗ ਮੁਲਾਂਕਣ ਰਿਪੋਰਟਾਂ', h3d: 'ਤੁਹਾਡੇ ਵੱਲੋਂ ਜਾਂਚੇ ਗਏ ਹਰ ਉਮੀਦਵਾਰ ਲਈ ਇੱਕ ਸਾਫ਼, ਸਾਂਝਾ ਕਰਨ ਯੋਗ .docx ਰਿਪੋਰਟ।',
      cta: 'ਮੁਫ਼ਤ ਅਜ਼ਮਾਓ',
    },
    contact: {
      label: 'ਸੰਪਰਕ ਕਰੋ', title: 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
      sub: 'ਸਵਾਲ, ਫੀਡਬੈਕ, ਜਾਂ ਸਾਂਝੇਦਾਰੀ ਦੇ ਵਿਚਾਰ — ਅਸੀਂ ਹਰ ਸੁਨੇਹਾ ਪੜ੍ਹਦੇ ਹਾਂ।',
      nameLabel: 'ਨਾਮ', emailLabel: 'ਈਮੇਲ', messageLabel: 'ਸੁਨੇਹਾ',
      send: 'ਸੁਨੇਹਾ ਭੇਜੋ', sending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ…',
      sentMsg: 'ਧੰਨਵਾਦ — ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ। ਅਸੀਂ ਜਲਦੀ ਹੀ ਤੁਹਾਨੂੰ ਜਵਾਬ ਦੇਵਾਂਗੇ।',
      errorGeneric: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।',
    },
  },

  zh: {
    nav: { about: '关于我们', services: '我们的服务', pricing: '价格', help: '帮助', contact: '联系我们', getStarted: '立即开始' },
    footer: {
      tagline: '跳过筛选机器人，直接触达真人招聘者。',
      product: '产品', services: '服务', pricing: '价格', tryFree: '免费试用',
      company: '公司', about: '关于我们', contact: '联系我们', terms: '服务条款', privacy: '隐私政策',
      followUs: '关注我们', rights: '版权所有。',
    },
    home: {
      badge: 'AI 驱动的简历定制',
      headline1: '您的简历可能在被人看到之前',
      headline2: '就已经被拒绝了。',
      sub: '大多数中大型企业在招聘人员打开申请之前，会先用 ATS 软件对其进行筛选。Resemy 会重写您的简历以通过筛选——并在修改前后都为您显示匹配分数。',
      ctaPrimary: '免费试用', ctaSecondary: '了解工作原理',
      stat1Value: '60 秒', stat1Label: '典型定制用时',
      stat2Value: '$0', stat2Label: '免费开始',
      stat3Label: '支持的语言数量',
      heroImgAlt: '一个人自信地在笔记本电脑上工作',
      problemLabel: '问题所在',
      problemTitle: '有资格，有经验，却仍被过滤掉。',
      problemDesc: '这几乎与您的能力无关。求职申请追踪系统（ATS）会扫描特定的关键词和结构——如果简历没有使用招聘信息中的确切措辞，往往根本无法送达任何一位招聘人员手中。',
      beforeLabel: '示例——定制前',
      beforeDesc: '通用简历，每次申请都一样——缺少这份工作正在寻找的确切关键词。',
      afterLabel: '示例——使用 Resemy 后',
      afterDesc: '同样真实的经历，用招聘信息本身的语言重新表述——没有任何虚构，只是换了表达方式。',
      howLabel: '使用流程', howTitle: '大约一分钟即可完成',
      step1Title: '上传您的简历', step1Desc: '一份 PDF、一份 DOCX，或直接粘贴文本——您现有的任何格式都可以。',
      step2Title: '粘贴职位描述', step2Desc: '完整的职位描述，让 Resemy 准确了解需要匹配的内容。',
      step3Title: '下载定制后的简历', step3Desc: '一份重写的简历、您的 ATS 与招聘经理匹配分数，以及接下来该做什么。',
      featuresLabel: '全部包含', featuresTitle: '远不止是重写简历',
      feature1Title: '定制简历', feature1Desc: '针对这个具体职位重写——绝不虚构经历。',
      feature2Title: '求职信与邮件', feature2Desc: '配套的求职信和简短的求职邮件，一并生成。',
      feature3Title: '推荐信初稿', feature3Desc: '为您的推荐人准备的初稿，供其个性化修改并签署。',
      feature4Title: '面试准备', feature4Desc: '可能被问到的问题、STAR 方法情景练习，以及您可以反问的问题。',
      feature5Title: '诚实的评分', feature5Desc: '查看真实的定制前后对比——以及实际仍然缺失的部分。',
      feature6Title: '同样适合招聘人员', feature6Desc: '使用我们的 HR 工具，几秒钟内即可根据职位描述评估候选人。',
      finalTitle: '不要再被系统过滤掉了。', finalSub: '免费开始，无需信用卡。', finalCta: '免费开始',
      globalTitle: '源自加拿大，为全世界而生。',
      globalSub: '无论您是在家门口求职，还是申请远在地球另一端的职位，Resemy 都以同样诚实的方式为每一个人服务——无论您的下一站在哪里。',
    },
    about: {
      label: '关于我们', title: '我们为什么创办 Resemy',
      p1: '在投出申请和从未收到回复之间的某个环节，一位真正有能力、有资格的人，被一个他们甚至不知道正在读取自己简历的软件筛掉了。Resemy 的存在，正是为了弥合这道差距——在有能力和被看见之间的差距。',
      p2: '我们创办 Resemy，是因为太多优秀的候选人被拒之门外，不是因为缺乏能力，而是因为缺少筛选软件正在寻找的那些确切词汇。我们相信这道差距值得被弥合——诚实地弥合，绝不虚构任何人并不具备的经历。',
      p3: 'Resemy 生成的每一次重写，都基于您简历中真实存在的内容——绝不编造成就，绝不夸大职责范围。比起给您一个不诚实的高分，我们更愿意如实告诉您真正的差距在哪里。',
    },
    services: {
      label: '我们的服务', title: '一个工具，覆盖招聘的两端',
      sub: '无论您是在求职还是在招聘，Resemy 都基于同一个诚实的原则：真实的信息，清晰的评分。',
      candidatesTitle: '面向求职者',
      c1t: '定制简历重写', c1d: '根据特定职位描述的语言和要求，重写您的简历。',
      c2t: 'ATS 与招聘经理评分', c2d: '诚实的定制前后对比分数，以及具体哪些关键词已匹配或仍缺失。',
      c3t: '求职信与求职邮件', c3d: '配套的求职信和简短、自信的求职邮件，一并生成。',
      c4t: '推荐信初稿', c4d: '为您的一位真实推荐人准备的初稿，供其个性化修改并签署。',
      c5t: '面试准备', c5d: '可能被问到的问题、示例回答、STAR 方法情景练习，以及可以反问的有见地的问题。',
      hrTitle: '面向人力资源与招聘人员',
      h1t: '候选人筛选', h1d: '上传候选人的简历和职位描述，即可获得即时且一致的评估。',
      h2t: '优势与差距分析', h2d: '已匹配的要求、缺失的要求，以及面试前值得再次确认的事项。',
      h3t: '可下载的评估报告', h3d: '为您筛选的每一位候选人生成清晰、可分享的 .docx 报告。',
      cta: '免费试用',
    },
    contact: {
      label: '联系我们', title: '联系我们',
      sub: '问题、反馈或合作想法——我们会阅读每一条留言。',
      nameLabel: '姓名', emailLabel: '电子邮箱', messageLabel: '留言内容',
      send: '发送留言', sending: '发送中…',
      sentMsg: '谢谢——您的留言已发送，我们会尽快回复您。',
      errorGeneric: '出现了一些问题。',
    },
  },
}